name: Install dependencies
description: Setup Yarn and Node.js and installs dependencies for the workflow
runs:
  using: composite
  steps:
    # This action assumes the repository has already been checked out
    - name: Setup Yarn
      shell: bash
      run: |
        corepack enable yarn
    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version: "22"
        cache: 'yarn'
    - name: Install dependencies
      shell: bash
      run: yarn install --immutable
