/* tslint:disable */
/* eslint-disable */
/**
 * Migration Planner Agent UI API
 * API endpoints for the agent UI to interact with the migration discovery VM
 *
 * The version of the OpenAPI document: undefined
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime.js';
import type {
  Credentials,
  InventoryReply,
  ServiceUIReply,
  StatusReply,
  VersionReply,
} from '../models/index.js';
import {
    CredentialsFromJSON,
    CredentialsToJSON,
    InventoryReplyFromJSON,
    InventoryReplyToJSON,
    ServiceUIReplyFromJSON,
    ServiceUIReplyToJSON,
    StatusReplyFromJSON,
    StatusReplyToJSON,
    VersionReplyFromJSON,
    VersionReplyToJSON,
} from '../models/index.js';

export interface SubmitCredentialsRequest {
    credentials: Credentials;
}

/**
 * AgentUiApi - interface
 * 
 * @export
 * @interface AgentUiApiInterface
 */
export interface AgentUiApiInterface {
    /**
     * Get the current status of the agent
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AgentUiApiInterface
     */
    getAgentStatusRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StatusReply>>;

    /**
     * Get the current status of the agent
     */
    getAgentStatus(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StatusReply>;

    /**
     * Get the version of the agent
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AgentUiApiInterface
     */
    getAgentVersionRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<VersionReply>>;

    /**
     * Get the version of the agent
     */
    getAgentVersion(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<VersionReply>;

    /**
     * Download the collected inventory data
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AgentUiApiInterface
     */
    getInventoryRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<InventoryReply>>;

    /**
     * Download the collected inventory data
     */
    getInventory(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<InventoryReply>;

    /**
     * Get the planner service UI URL
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AgentUiApiInterface
     */
    getPlannerUrlRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ServiceUIReply>>;

    /**
     * Get the planner service UI URL
     */
    getPlannerUrl(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ServiceUIReply>;

    /**
     * Submit VMware credentials for the discovery process
     * @param {Credentials} credentials 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AgentUiApiInterface
     */
    submitCredentialsRaw(requestParameters: SubmitCredentialsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Submit VMware credentials for the discovery process
     */
    submitCredentials(requestParameters: SubmitCredentialsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

}

/**
 * 
 */
export class AgentUiApi extends runtime.BaseAPI implements AgentUiApiInterface {

    /**
     * Get the current status of the agent
     */
    async getAgentStatusRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StatusReply>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/status`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StatusReplyFromJSON(jsonValue));
    }

    /**
     * Get the current status of the agent
     */
    async getAgentStatus(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StatusReply> {
        const response = await this.getAgentStatusRaw(initOverrides);
        return await response.value();
    }

    /**
     * Get the version of the agent
     */
    async getAgentVersionRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<VersionReply>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/version`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => VersionReplyFromJSON(jsonValue));
    }

    /**
     * Get the version of the agent
     */
    async getAgentVersion(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<VersionReply> {
        const response = await this.getAgentVersionRaw(initOverrides);
        return await response.value();
    }

    /**
     * Download the collected inventory data
     */
    async getInventoryRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<InventoryReply>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/inventory`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => InventoryReplyFromJSON(jsonValue));
    }

    /**
     * Download the collected inventory data
     */
    async getInventory(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<InventoryReply> {
        const response = await this.getInventoryRaw(initOverrides);
        return await response.value();
    }

    /**
     * Get the planner service UI URL
     */
    async getPlannerUrlRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ServiceUIReply>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/url`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ServiceUIReplyFromJSON(jsonValue));
    }

    /**
     * Get the planner service UI URL
     */
    async getPlannerUrl(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ServiceUIReply> {
        const response = await this.getPlannerUrlRaw(initOverrides);
        return await response.value();
    }

    /**
     * Submit VMware credentials for the discovery process
     */
    async submitCredentialsRaw(requestParameters: SubmitCredentialsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['credentials'] == null) {
            throw new runtime.RequiredError(
                'credentials',
                'Required parameter "credentials" was null or undefined when calling submitCredentials().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/credentials`;

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: CredentialsToJSON(requestParameters['credentials']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Submit VMware credentials for the discovery process
     */
    async submitCredentials(requestParameters: SubmitCredentialsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.submitCredentialsRaw(requestParameters, initOverrides);
    }

}
