/* tslint:disable */
/* eslint-disable */
/**
 * Migration Planner API - agent endpoint
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: undefined
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime.js';
import type {
  AgentStatusUpdate,
} from '../models/index.js';
import {
    AgentStatusUpdateFromJSON,
    AgentStatusUpdateToJSON,
} from '../models/index.js';

export interface UpdateAgentStatusRequest {
    id: string;
    agentStatusUpdate?: AgentStatusUpdate;
}

/**
 * AgentApi - interface
 * 
 * @export
 * @interface AgentApiInterface
 */
export interface AgentApiInterface {
    /**
     * Update status of the agent
     * @param {string} id ID the agent
     * @param {AgentStatusUpdate} [agentStatusUpdate] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AgentApiInterface
     */
    updateAgentStatusRaw(requestParameters: UpdateAgentStatusRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Update status of the agent
     */
    updateAgentStatus(requestParameters: UpdateAgentStatusRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

}

/**
 * 
 */
export class AgentApi extends runtime.BaseAPI implements AgentApiInterface {

    /**
     * Update status of the agent
     */
    async updateAgentStatusRaw(requestParameters: UpdateAgentStatusRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling updateAgentStatus().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/agents/{id}/status`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: AgentStatusUpdateToJSON(requestParameters['agentStatusUpdate']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Update status of the agent
     */
    async updateAgentStatus(requestParameters: UpdateAgentStatusRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.updateAgentStatusRaw(requestParameters, initOverrides);
    }

}
