/* tslint:disable */
/* eslint-disable */
/**
 * Assisted Migration Agent API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime.js';
import type {
  AgentModeRequest,
  AgentStatus,
  CollectorStartRequest,
  CollectorStatus,
  CreateGroupRequest,
  GetInventory200Response,
  Group,
  GroupListResponse,
  GroupResponse,
  InspectorStartRequest,
  InspectorStatus,
  UpdateGroupRequest,
  VddkPost200Response,
  VddkPostRequest,
  VersionInfo,
  VirtualMachineDetail,
  VirtualMachineListResponse,
  VmInspectionStatus,
} from '../models/index.js';
import {
    AgentModeRequestFromJSON,
    AgentModeRequestToJSON,
    AgentStatusFromJSON,
    AgentStatusToJSON,
    CollectorStartRequestFromJSON,
    CollectorStartRequestToJSON,
    CollectorStatusFromJSON,
    CollectorStatusToJSON,
    CreateGroupRequestFromJSON,
    CreateGroupRequestToJSON,
    GetInventory200ResponseFromJSON,
    GetInventory200ResponseToJSON,
    GroupFromJSON,
    GroupToJSON,
    GroupListResponseFromJSON,
    GroupListResponseToJSON,
    GroupResponseFromJSON,
    GroupResponseToJSON,
    InspectorStartRequestFromJSON,
    InspectorStartRequestToJSON,
    InspectorStatusFromJSON,
    InspectorStatusToJSON,
    UpdateGroupRequestFromJSON,
    UpdateGroupRequestToJSON,
    VddkPost200ResponseFromJSON,
    VddkPost200ResponseToJSON,
    VddkPostRequestFromJSON,
    VddkPostRequestToJSON,
    VersionInfoFromJSON,
    VersionInfoToJSON,
    VirtualMachineDetailFromJSON,
    VirtualMachineDetailToJSON,
    VirtualMachineListResponseFromJSON,
    VirtualMachineListResponseToJSON,
    VmInspectionStatusFromJSON,
    VmInspectionStatusToJSON,
} from '../models/index.js';

export interface AddVMsToInspectionRequest {
    requestBody: Array<string>;
}

export interface CreateGroupOperationRequest {
    createGroupRequest: CreateGroupRequest;
}

export interface DeleteGroupRequest {
    id: string;
}

export interface GetGroupRequest {
    id: string;
    sort?: Array<string>;
    page?: number;
    pageSize?: number;
}

export interface GetInventoryRequest {
    withAgentId?: boolean;
    groupId?: string;
}

export interface GetVMRequest {
    id: string;
}

export interface GetVMInspectionStatusRequest {
    id: string;
}

export interface GetVMsRequest {
    byExpression?: string;
    sort?: Array<string>;
    page?: number;
    pageSize?: number;
}

export interface ListGroupsRequest {
    byName?: string;
    page?: number;
    pageSize?: number;
}

export interface RemoveVMFromInspectionRequest {
    id: string;
}

export interface SetAgentModeRequest {
    agentModeRequest: AgentModeRequest;
}

export interface StartCollectorRequest {
    collectorStartRequest: CollectorStartRequest;
}

export interface StartInspectionRequest {
    inspectorStartRequest: InspectorStartRequest;
}

export interface UpdateGroupOperationRequest {
    id: string;
    updateGroupRequest: UpdateGroupRequest;
}

export interface VddkPostOperationRequest {
    vddkPostRequest: VddkPostRequest;
}

/**
 * DefaultApi - interface
 * 
 * @export
 * @interface DefaultApiInterface
 */
export interface DefaultApiInterface {
    /**
     * 
     * @summary Add more VMs to inspection queue
     * @param {Array<string>} requestBody 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    addVMsToInspectionRaw(requestParameters: AddVMsToInspectionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<InspectorStatus>>;

    /**
     * Add more VMs to inspection queue
     */
    addVMsToInspection(requestParameters: AddVMsToInspectionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<InspectorStatus>;

    /**
     * 
     * @summary Create a new group
     * @param {CreateGroupRequest} createGroupRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    createGroupRaw(requestParameters: CreateGroupOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Group>>;

    /**
     * Create a new group
     */
    createGroup(requestParameters: CreateGroupOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Group>;

    /**
     * 
     * @summary Delete group
     * @param {string} id Group ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    deleteGroupRaw(requestParameters: DeleteGroupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Delete group
     */
    deleteGroup(requestParameters: DeleteGroupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * 
     * @summary Get agent status
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    getAgentStatusRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AgentStatus>>;

    /**
     * Get agent status
     */
    getAgentStatus(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AgentStatus>;

    /**
     * 
     * @summary Get collector status
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    getCollectorStatusRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CollectorStatus>>;

    /**
     * Get collector status
     */
    getCollectorStatus(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CollectorStatus>;

    /**
     * 
     * @summary Get group by ID with its VMs
     * @param {string} id Group ID
     * @param {Array<string>} [sort] Sort fields with direction (e.g., \&quot;name:asc\&quot; or \&quot;cluster:desc,name:asc\&quot;). Valid fields are name, vCenterState, cluster, diskSize, memory, issues.
     * @param {number} [page] Page number for pagination
     * @param {number} [pageSize] Number of items per page
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    getGroupRaw(requestParameters: GetGroupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GroupResponse>>;

    /**
     * Get group by ID with its VMs
     */
    getGroup(requestParameters: GetGroupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GroupResponse>;

    /**
     * 
     * @summary Get inspector status
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    getInspectorStatusRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<InspectorStatus>>;

    /**
     * Get inspector status
     */
    getInspectorStatus(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<InspectorStatus>;

    /**
     * 
     * @summary Get collected inventory
     * @param {boolean} [withAgentId] If true, include the agentId in the response (Compatible with manual inventory upload).
     * @param {string} [groupId] Filter inventory to VMs matching this group\&#39;s filter expression
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    getInventoryRaw(requestParameters: GetInventoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetInventory200Response>>;

    /**
     * Get collected inventory
     */
    getInventory(requestParameters: GetInventoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetInventory200Response>;

    /**
     * 
     * @summary Get details about a vm
     * @param {string} id VirtualMachine id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    getVMRaw(requestParameters: GetVMRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<VirtualMachineDetail>>;

    /**
     * Get details about a vm
     */
    getVM(requestParameters: GetVMRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<VirtualMachineDetail>;

    /**
     * 
     * @summary Get inspection status for a specific VirtualMachine
     * @param {string} id VirtualMachine ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    getVMInspectionStatusRaw(requestParameters: GetVMInspectionStatusRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<VmInspectionStatus>>;

    /**
     * Get inspection status for a specific VirtualMachine
     */
    getVMInspectionStatus(requestParameters: GetVMInspectionStatusRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<VmInspectionStatus>;

    /**
     * 
     * @summary Get list of VMs with filtering and pagination
     * @param {string} [byExpression] Filter by expression (matches VMs with the provided expression)
     * @param {Array<string>} [sort] Sort fields with direction (e.g., \&quot;name:asc\&quot; or \&quot;cluster:desc,name:asc\&quot;). Valid fields are name, vCenterState, cluster, diskSize, memory, issues.
     * @param {number} [page] Page number for pagination
     * @param {number} [pageSize] Number of items per page
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    getVMsRaw(requestParameters: GetVMsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<VirtualMachineListResponse>>;

    /**
     * Get list of VMs with filtering and pagination
     */
    getVMs(requestParameters: GetVMsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<VirtualMachineListResponse>;

    /**
     * 
     * @summary Get agent version information
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    getVersionRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<VersionInfo>>;

    /**
     * Get agent version information
     */
    getVersion(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<VersionInfo>;

    /**
     * 
     * @summary List all groups
     * @param {string} [byName] Filter groups by name (case-insensitive substring match)
     * @param {number} [page] Page number (1-indexed)
     * @param {number} [pageSize] Number of groups per page
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    listGroupsRaw(requestParameters: ListGroupsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GroupListResponse>>;

    /**
     * List all groups
     */
    listGroups(requestParameters: ListGroupsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GroupListResponse>;

    /**
     * 
     * @summary Remove VirtualMachine from inspection queue
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    removeVMFromInspectionRaw(requestParameters: RemoveVMFromInspectionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<VmInspectionStatus>>;

    /**
     * Remove VirtualMachine from inspection queue
     */
    removeVMFromInspection(requestParameters: RemoveVMFromInspectionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<VmInspectionStatus>;

    /**
     * 
     * @summary Change agent mode
     * @param {AgentModeRequest} agentModeRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    setAgentModeRaw(requestParameters: SetAgentModeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AgentStatus>>;

    /**
     * Change agent mode
     */
    setAgentMode(requestParameters: SetAgentModeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AgentStatus>;

    /**
     * 
     * @summary Start inventory collection
     * @param {CollectorStartRequest} collectorStartRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    startCollectorRaw(requestParameters: StartCollectorRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CollectorStatus>>;

    /**
     * Start inventory collection
     */
    startCollector(requestParameters: StartCollectorRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CollectorStatus>;

    /**
     * 
     * @summary Start inspection for VMs
     * @param {InspectorStartRequest} inspectorStartRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    startInspectionRaw(requestParameters: StartInspectionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<InspectorStatus>>;

    /**
     * Start inspection for VMs
     */
    startInspection(requestParameters: StartInspectionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<InspectorStatus>;

    /**
     * 
     * @summary Stop collection
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    stopCollectorRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Stop collection
     */
    stopCollector(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * 
     * @summary Stop inspector entirely
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    stopInspectionRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<InspectorStatus>>;

    /**
     * Stop inspector entirely
     */
    stopInspection(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<InspectorStatus>;

    /**
     * 
     * @summary Update group
     * @param {string} id Group ID
     * @param {UpdateGroupRequest} updateGroupRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    updateGroupRaw(requestParameters: UpdateGroupOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Group>>;

    /**
     * Update group
     */
    updateGroup(requestParameters: UpdateGroupOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Group>;

    /**
     * 
     * @summary Upload VDDK tarball
     * @param {VddkPostRequest} vddkPostRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    vddkPostRaw(requestParameters: VddkPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<VddkPost200Response>>;

    /**
     * Upload VDDK tarball
     */
    vddkPost(requestParameters: VddkPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<VddkPost200Response>;

}

/**
 * 
 */
export class DefaultApi extends runtime.BaseAPI implements DefaultApiInterface {

    /**
     * Add more VMs to inspection queue
     */
    async addVMsToInspectionRaw(requestParameters: AddVMsToInspectionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<InspectorStatus>> {
        if (requestParameters['requestBody'] == null) {
            throw new runtime.RequiredError(
                'requestBody',
                'Required parameter "requestBody" was null or undefined when calling addVMsToInspection().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/vms/inspector`;

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['requestBody'],
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => InspectorStatusFromJSON(jsonValue));
    }

    /**
     * Add more VMs to inspection queue
     */
    async addVMsToInspection(requestParameters: AddVMsToInspectionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<InspectorStatus> {
        const response = await this.addVMsToInspectionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create a new group
     */
    async createGroupRaw(requestParameters: CreateGroupOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Group>> {
        if (requestParameters['createGroupRequest'] == null) {
            throw new runtime.RequiredError(
                'createGroupRequest',
                'Required parameter "createGroupRequest" was null or undefined when calling createGroup().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/vms/groups`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateGroupRequestToJSON(requestParameters['createGroupRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GroupFromJSON(jsonValue));
    }

    /**
     * Create a new group
     */
    async createGroup(requestParameters: CreateGroupOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Group> {
        const response = await this.createGroupRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete group
     */
    async deleteGroupRaw(requestParameters: DeleteGroupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteGroup().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/vms/groups/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete group
     */
    async deleteGroup(requestParameters: DeleteGroupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteGroupRaw(requestParameters, initOverrides);
    }

    /**
     * Get agent status
     */
    async getAgentStatusRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AgentStatus>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/agent`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AgentStatusFromJSON(jsonValue));
    }

    /**
     * Get agent status
     */
    async getAgentStatus(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AgentStatus> {
        const response = await this.getAgentStatusRaw(initOverrides);
        return await response.value();
    }

    /**
     * Get collector status
     */
    async getCollectorStatusRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CollectorStatus>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/collector`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CollectorStatusFromJSON(jsonValue));
    }

    /**
     * Get collector status
     */
    async getCollectorStatus(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CollectorStatus> {
        const response = await this.getCollectorStatusRaw(initOverrides);
        return await response.value();
    }

    /**
     * Get group by ID with its VMs
     */
    async getGroupRaw(requestParameters: GetGroupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GroupResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getGroup().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['sort'] != null) {
            queryParameters['sort'] = requestParameters['sort'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['pageSize'] = requestParameters['pageSize'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/vms/groups/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GroupResponseFromJSON(jsonValue));
    }

    /**
     * Get group by ID with its VMs
     */
    async getGroup(requestParameters: GetGroupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GroupResponse> {
        const response = await this.getGroupRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get inspector status
     */
    async getInspectorStatusRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<InspectorStatus>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/vms/inspector`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => InspectorStatusFromJSON(jsonValue));
    }

    /**
     * Get inspector status
     */
    async getInspectorStatus(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<InspectorStatus> {
        const response = await this.getInspectorStatusRaw(initOverrides);
        return await response.value();
    }

    /**
     * Get collected inventory
     */
    async getInventoryRaw(requestParameters: GetInventoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetInventory200Response>> {
        const queryParameters: any = {};

        if (requestParameters['withAgentId'] != null) {
            queryParameters['withAgentId'] = requestParameters['withAgentId'];
        }

        if (requestParameters['groupId'] != null) {
            queryParameters['group_id'] = requestParameters['groupId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/inventory`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetInventory200ResponseFromJSON(jsonValue));
    }

    /**
     * Get collected inventory
     */
    async getInventory(requestParameters: GetInventoryRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetInventory200Response> {
        const response = await this.getInventoryRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get details about a vm
     */
    async getVMRaw(requestParameters: GetVMRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<VirtualMachineDetail>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getVM().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/vms/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => VirtualMachineDetailFromJSON(jsonValue));
    }

    /**
     * Get details about a vm
     */
    async getVM(requestParameters: GetVMRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<VirtualMachineDetail> {
        const response = await this.getVMRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get inspection status for a specific VirtualMachine
     */
    async getVMInspectionStatusRaw(requestParameters: GetVMInspectionStatusRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<VmInspectionStatus>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getVMInspectionStatus().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/vms/{id}/inspector`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => VmInspectionStatusFromJSON(jsonValue));
    }

    /**
     * Get inspection status for a specific VirtualMachine
     */
    async getVMInspectionStatus(requestParameters: GetVMInspectionStatusRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<VmInspectionStatus> {
        const response = await this.getVMInspectionStatusRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get list of VMs with filtering and pagination
     */
    async getVMsRaw(requestParameters: GetVMsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<VirtualMachineListResponse>> {
        const queryParameters: any = {};

        if (requestParameters['byExpression'] != null) {
            queryParameters['byExpression'] = requestParameters['byExpression'];
        }

        if (requestParameters['sort'] != null) {
            queryParameters['sort'] = requestParameters['sort'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['pageSize'] = requestParameters['pageSize'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/vms`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => VirtualMachineListResponseFromJSON(jsonValue));
    }

    /**
     * Get list of VMs with filtering and pagination
     */
    async getVMs(requestParameters: GetVMsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<VirtualMachineListResponse> {
        const response = await this.getVMsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get agent version information
     */
    async getVersionRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<VersionInfo>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/version`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => VersionInfoFromJSON(jsonValue));
    }

    /**
     * Get agent version information
     */
    async getVersion(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<VersionInfo> {
        const response = await this.getVersionRaw(initOverrides);
        return await response.value();
    }

    /**
     * List all groups
     */
    async listGroupsRaw(requestParameters: ListGroupsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GroupListResponse>> {
        const queryParameters: any = {};

        if (requestParameters['byName'] != null) {
            queryParameters['byName'] = requestParameters['byName'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['pageSize'] = requestParameters['pageSize'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/vms/groups`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GroupListResponseFromJSON(jsonValue));
    }

    /**
     * List all groups
     */
    async listGroups(requestParameters: ListGroupsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GroupListResponse> {
        const response = await this.listGroupsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Remove VirtualMachine from inspection queue
     */
    async removeVMFromInspectionRaw(requestParameters: RemoveVMFromInspectionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<VmInspectionStatus>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling removeVMFromInspection().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/vms/{id}/inspector`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => VmInspectionStatusFromJSON(jsonValue));
    }

    /**
     * Remove VirtualMachine from inspection queue
     */
    async removeVMFromInspection(requestParameters: RemoveVMFromInspectionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<VmInspectionStatus> {
        const response = await this.removeVMFromInspectionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Change agent mode
     */
    async setAgentModeRaw(requestParameters: SetAgentModeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AgentStatus>> {
        if (requestParameters['agentModeRequest'] == null) {
            throw new runtime.RequiredError(
                'agentModeRequest',
                'Required parameter "agentModeRequest" was null or undefined when calling setAgentMode().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/agent`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AgentModeRequestToJSON(requestParameters['agentModeRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AgentStatusFromJSON(jsonValue));
    }

    /**
     * Change agent mode
     */
    async setAgentMode(requestParameters: SetAgentModeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AgentStatus> {
        const response = await this.setAgentModeRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Start inventory collection
     */
    async startCollectorRaw(requestParameters: StartCollectorRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CollectorStatus>> {
        if (requestParameters['collectorStartRequest'] == null) {
            throw new runtime.RequiredError(
                'collectorStartRequest',
                'Required parameter "collectorStartRequest" was null or undefined when calling startCollector().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/collector`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CollectorStartRequestToJSON(requestParameters['collectorStartRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CollectorStatusFromJSON(jsonValue));
    }

    /**
     * Start inventory collection
     */
    async startCollector(requestParameters: StartCollectorRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CollectorStatus> {
        const response = await this.startCollectorRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Start inspection for VMs
     */
    async startInspectionRaw(requestParameters: StartInspectionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<InspectorStatus>> {
        if (requestParameters['inspectorStartRequest'] == null) {
            throw new runtime.RequiredError(
                'inspectorStartRequest',
                'Required parameter "inspectorStartRequest" was null or undefined when calling startInspection().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/vms/inspector`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: InspectorStartRequestToJSON(requestParameters['inspectorStartRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => InspectorStatusFromJSON(jsonValue));
    }

    /**
     * Start inspection for VMs
     */
    async startInspection(requestParameters: StartInspectionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<InspectorStatus> {
        const response = await this.startInspectionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Stop collection
     */
    async stopCollectorRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/collector`;

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Stop collection
     */
    async stopCollector(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.stopCollectorRaw(initOverrides);
    }

    /**
     * Stop inspector entirely
     */
    async stopInspectionRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<InspectorStatus>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/vms/inspector`;

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => InspectorStatusFromJSON(jsonValue));
    }

    /**
     * Stop inspector entirely
     */
    async stopInspection(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<InspectorStatus> {
        const response = await this.stopInspectionRaw(initOverrides);
        return await response.value();
    }

    /**
     * Update group
     */
    async updateGroupRaw(requestParameters: UpdateGroupOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Group>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling updateGroup().'
            );
        }

        if (requestParameters['updateGroupRequest'] == null) {
            throw new runtime.RequiredError(
                'updateGroupRequest',
                'Required parameter "updateGroupRequest" was null or undefined when calling updateGroup().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/vms/groups/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateGroupRequestToJSON(requestParameters['updateGroupRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GroupFromJSON(jsonValue));
    }

    /**
     * Update group
     */
    async updateGroup(requestParameters: UpdateGroupOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Group> {
        const response = await this.updateGroupRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Upload VDDK tarball
     */
    async vddkPostRaw(requestParameters: VddkPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<VddkPost200Response>> {
        if (requestParameters['vddkPostRequest'] == null) {
            throw new runtime.RequiredError(
                'vddkPostRequest',
                'Required parameter "vddkPostRequest" was null or undefined when calling vddkPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'multiple/form-data';


        let urlPath = `/vddk`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: VddkPostRequestToJSON(requestParameters['vddkPostRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => VddkPost200ResponseFromJSON(jsonValue));
    }

    /**
     * Upload VDDK tarball
     */
    async vddkPost(requestParameters: VddkPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<VddkPost200Response> {
        const response = await this.vddkPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
