/* tslint:disable */
/* eslint-disable */
/**
 * Migration Planner API - agent endpoint
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: undefined
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime.js';
import type {
  Source,
  SourceStatusUpdate,
} from '../models/index.js';
import {
    SourceFromJSON,
    SourceToJSON,
    SourceStatusUpdateFromJSON,
    SourceStatusUpdateToJSON,
} from '../models/index.js';

export interface UpdateSourceInventoryRequest {
    id: string;
    sourceStatusUpdate: SourceStatusUpdate;
}

/**
 * SourceApi - interface
 * 
 * @export
 * @interface SourceApiInterface
 */
export interface SourceApiInterface {
    /**
     * Updates the inventory of a source
     * @param {string} id ID of the source
     * @param {SourceStatusUpdate} sourceStatusUpdate 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SourceApiInterface
     */
    updateSourceInventoryRaw(requestParameters: UpdateSourceInventoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Source>>;

    /**
     * Updates the inventory of a source
     */
    updateSourceInventory(requestParameters: UpdateSourceInventoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Source>;

}

/**
 * 
 */
export class SourceApi extends runtime.BaseAPI implements SourceApiInterface {

    /**
     * Updates the inventory of a source
     */
    async updateSourceInventoryRaw(requestParameters: UpdateSourceInventoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Source>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling updateSourceInventory().'
            );
        }

        if (requestParameters['sourceStatusUpdate'] == null) {
            throw new runtime.RequiredError(
                'sourceStatusUpdate',
                'Required parameter "sourceStatusUpdate" was null or undefined when calling updateSourceInventory().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/sources/{id}/status`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: SourceStatusUpdateToJSON(requestParameters['sourceStatusUpdate']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SourceFromJSON(jsonValue));
    }

    /**
     * Updates the inventory of a source
     */
    async updateSourceInventory(requestParameters: UpdateSourceInventoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Source> {
        const response = await this.updateSourceInventoryRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
