/* tslint:disable */
/* eslint-disable */
/**
 * Migration Planner API
 * Based on: https://github.com/kubev2v/migration-planner/blob/bd435bf4e63611a5d609f7c918e85dd57830fccf/api/v1alpha1/openapi.yaml
 *
 * The version of the OpenAPI document: 0.4.0-bd435bf4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface AgentProxy
 */
export interface AgentProxy {
    /**
     * 
     * @type {string}
     * @memberof AgentProxy
     */
    httpUrl?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AgentProxy
     */
    httpsUrl?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AgentProxy
     */
    noProxy?: string | null;
}

/**
 * Check if a given object implements the AgentProxy interface.
 */
export function instanceOfAgentProxy(value: object): value is AgentProxy {
    return true;
}

export function AgentProxyFromJSON(json: any): AgentProxy {
    return AgentProxyFromJSONTyped(json, false);
}

export function AgentProxyFromJSONTyped(json: any, ignoreDiscriminator: boolean): AgentProxy {
    if (json == null) {
        return json;
    }
    return {
        
        'httpUrl': json['httpUrl'] == null ? undefined : json['httpUrl'],
        'httpsUrl': json['httpsUrl'] == null ? undefined : json['httpsUrl'],
        'noProxy': json['noProxy'] == null ? undefined : json['noProxy'],
    };
}

export function AgentProxyToJSON(json: any): AgentProxy {
    return AgentProxyToJSONTyped(json, false);
}

export function AgentProxyToJSONTyped(value?: AgentProxy | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'httpUrl': value['httpUrl'],
        'httpsUrl': value['httpsUrl'],
        'noProxy': value['noProxy'],
    };
}

