/* tslint:disable */
/* eslint-disable */
/**
 * Migration Planner API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: undefined
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AssessmentForm
 */
export interface AssessmentForm {
    /**
     * 
     * @type {string}
     * @memberof AssessmentForm
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof AssessmentForm
     */
    sourceID: string;
}

/**
 * Check if a given object implements the AssessmentForm interface.
 */
export function instanceOfAssessmentForm(value: object): value is AssessmentForm {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('sourceID' in value) || value['sourceID'] === undefined) return false;
    return true;
}

export function AssessmentFormFromJSON(json: any): AssessmentForm {
    return AssessmentFormFromJSONTyped(json, false);
}

export function AssessmentFormFromJSONTyped(json: any, ignoreDiscriminator: boolean): AssessmentForm {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'sourceID': json['sourceID'],
    };
}

export function AssessmentFormToJSON(value?: AssessmentForm | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'sourceID': value['sourceID'],
    };
}

