/* tslint:disable */
/* eslint-disable */
/**
 * Migration Planner API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: undefined
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Inventory } from './Inventory';
import {
    InventoryFromJSON,
    InventoryFromJSONTyped,
    InventoryToJSON,
} from './Inventory';

/**
 * 
 * @export
 * @interface Assessment
 */
export interface Assessment {
    /**
     * 
     * @type {string}
     * @memberof Assessment
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof Assessment
     */
    name: string;
    /**
     * 
     * @type {Date}
     * @memberof Assessment
     */
    createdAt: Date;
    /**
     * 
     * @type {Inventory}
     * @memberof Assessment
     */
    inventory: Inventory;
    /**
     * 
     * @type {string}
     * @memberof Assessment
     */
    sourceID: string;
}

/**
 * Check if a given object implements the Assessment interface.
 */
export function instanceOfAssessment(value: object): value is Assessment {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('inventory' in value) || value['inventory'] === undefined) return false;
    if (!('sourceID' in value) || value['sourceID'] === undefined) return false;
    return true;
}

export function AssessmentFromJSON(json: any): Assessment {
    return AssessmentFromJSONTyped(json, false);
}

export function AssessmentFromJSONTyped(json: any, ignoreDiscriminator: boolean): Assessment {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'createdAt': (new Date(json['createdAt'])),
        'inventory': InventoryFromJSON(json['inventory']),
        'sourceID': json['sourceID'],
    };
}

export function AssessmentToJSON(value?: Assessment | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'name': value['name'],
        'createdAt': ((value['createdAt']).toISOString()),
        'inventory': InventoryToJSON(value['inventory']),
        'sourceID': value['sourceID'],
    };
}

