/* tslint:disable */
/* eslint-disable */
/**
 * Migration Planner API
 * Based on: https://github.com/kubev2v/migration-planner/blob/381e0e2f0d99c996a1230d27470988d7cbe9e282/api/v1alpha1/openapi.yaml
 *
 * The version of the OpenAPI document: 0.4.0-381e0e2f
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { Inventory } from './Inventory.js';
import {
    InventoryFromJSON,
    InventoryFromJSONTyped,
    InventoryToJSON,
    InventoryToJSONTyped,
} from './Inventory.js';

/**
 * 
 * @export
 * @interface AssessmentForm
 */
export interface AssessmentForm {
    /**
     * 
     * @type {string}
     * @memberof AssessmentForm
     */
    name: string;
    /**
     * Source of the assessment data:
     *  * `inventory` - Manual inventory upload via JSON
     *  * `agent` - Collected by migration planner agent
     * 
     * @type {string}
     * @memberof AssessmentForm
     */
    sourceType: string;
    /**
     * 
     * @type {string}
     * @memberof AssessmentForm
     */
    sourceId?: string;
    /**
     * 
     * @type {Inventory}
     * @memberof AssessmentForm
     */
    inventory?: Inventory;
}

/**
 * Check if a given object implements the AssessmentForm interface.
 */
export function instanceOfAssessmentForm(value: object): value is AssessmentForm {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('sourceType' in value) || value['sourceType'] === undefined) return false;
    return true;
}

export function AssessmentFormFromJSON(json: any): AssessmentForm {
    return AssessmentFormFromJSONTyped(json, false);
}

export function AssessmentFormFromJSONTyped(json: any, ignoreDiscriminator: boolean): AssessmentForm {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'sourceType': json['sourceType'],
        'sourceId': json['sourceId'] == null ? undefined : json['sourceId'],
        'inventory': json['inventory'] == null ? undefined : InventoryFromJSON(json['inventory']),
    };
}

export function AssessmentFormToJSON(json: any): AssessmentForm {
    return AssessmentFormToJSONTyped(json, false);
}

export function AssessmentFormToJSONTyped(value?: AssessmentForm | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'sourceType': value['sourceType'],
        'sourceId': value['sourceId'],
        'inventory': InventoryToJSON(value['inventory']),
    };
}

