/* tslint:disable */
/* eslint-disable */
/**
 * Migration Planner API
 * Based on: https://github.com/kubev2v/migration-planner/blob/381e0e2f0d99c996a1230d27470988d7cbe9e282/api/v1alpha1/openapi.yaml
 *
 * The version of the OpenAPI document: 0.4.0-381e0e2f
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * Update form of the assessment.
 * @export
 * @interface AssessmentUpdate
 */
export interface AssessmentUpdate {
    /**
     * Name of the assessment
     * @type {string}
     * @memberof AssessmentUpdate
     */
    name?: string;
}

/**
 * Check if a given object implements the AssessmentUpdate interface.
 */
export function instanceOfAssessmentUpdate(value: object): value is AssessmentUpdate {
    return true;
}

export function AssessmentUpdateFromJSON(json: any): AssessmentUpdate {
    return AssessmentUpdateFromJSONTyped(json, false);
}

export function AssessmentUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): AssessmentUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function AssessmentUpdateToJSON(json: any): AssessmentUpdate {
    return AssessmentUpdateToJSONTyped(json, false);
}

export function AssessmentUpdateToJSONTyped(value?: AssessmentUpdate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
    };
}

