/* tslint:disable */
/* eslint-disable */
/**
 * Migration Planner API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: undefined
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { Snapshot } from './Snapshot.js';
import {
    SnapshotFromJSON,
    SnapshotFromJSONTyped,
    SnapshotToJSON,
    SnapshotToJSONTyped,
} from './Snapshot.js';

/**
 * 
 * @export
 * @interface Assessment
 */
export interface Assessment {
    /**
     * 
     * @type {string}
     * @memberof Assessment
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof Assessment
     */
    name: string;
    /**
     * Owner's first name
     * @type {string}
     * @memberof Assessment
     */
    ownerFirstName?: string;
    /**
     * Owner's last name
     * @type {string}
     * @memberof Assessment
     */
    ownerLastName?: string;
    /**
     * 
     * @type {string}
     * @memberof Assessment
     */
    sourceType: AssessmentSourceTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof Assessment
     */
    sourceId?: string;
    /**
     * 
     * @type {Date}
     * @memberof Assessment
     */
    createdAt: Date;
    /**
     * 
     * @type {Array<Snapshot>}
     * @memberof Assessment
     */
    snapshots: Array<Snapshot>;
}


/**
 * @export
 */
export const AssessmentSourceTypeEnum = {
    Inventory: 'inventory',
    Rvtools: 'rvtools',
    Source: 'source'
} as const;
export type AssessmentSourceTypeEnum = typeof AssessmentSourceTypeEnum[keyof typeof AssessmentSourceTypeEnum];


/**
 * Check if a given object implements the Assessment interface.
 */
export function instanceOfAssessment(value: object): value is Assessment {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('sourceType' in value) || value['sourceType'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('snapshots' in value) || value['snapshots'] === undefined) return false;
    return true;
}

export function AssessmentFromJSON(json: any): Assessment {
    return AssessmentFromJSONTyped(json, false);
}

export function AssessmentFromJSONTyped(json: any, ignoreDiscriminator: boolean): Assessment {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'ownerFirstName': json['ownerFirstName'] == null ? undefined : json['ownerFirstName'],
        'ownerLastName': json['ownerLastName'] == null ? undefined : json['ownerLastName'],
        'sourceType': json['sourceType'],
        'sourceId': json['sourceId'] == null ? undefined : json['sourceId'],
        'createdAt': (new Date(json['createdAt'])),
        'snapshots': ((json['snapshots'] as Array<any>).map(SnapshotFromJSON)),
    };
}

export function AssessmentToJSON(json: any): Assessment {
    return AssessmentToJSONTyped(json, false);
}

export function AssessmentToJSONTyped(value?: Assessment | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'ownerFirstName': value['ownerFirstName'],
        'ownerLastName': value['ownerLastName'],
        'sourceType': value['sourceType'],
        'sourceId': value['sourceId'],
        'createdAt': value['createdAt'].toISOString(),
        'snapshots': ((value['snapshots'] as Array<any>).map(SnapshotToJSON)),
    };
}

