/* tslint:disable */
/* eslint-disable */
/**
 * Migration Planner API
 * Based on: https://github.com/kubev2v/migration-planner/blob/381e0e2f0d99c996a1230d27470988d7cbe9e282/api/v1alpha1/openapi.yaml
 *
 * The version of the OpenAPI document: 0.4.0-381e0e2f
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * Overall cluster sizing summary
 * @export
 * @interface ClusterSizing
 */
export interface ClusterSizing {
    /**
     * Total number of nodes (worker + control plane)
     * @type {number}
     * @memberof ClusterSizing
     */
    totalNodes: number;
    /**
     * Number of worker nodes
     * @type {number}
     * @memberof ClusterSizing
     */
    workerNodes: number;
    /**
     * Number of control plane nodes
     * @type {number}
     * @memberof ClusterSizing
     */
    controlPlaneNodes: number;
    /**
     * Total CPU cores across all nodes
     * @type {number}
     * @memberof ClusterSizing
     */
    totalCPU: number;
    /**
     * Total memory (GB) across all nodes
     * @type {number}
     * @memberof ClusterSizing
     */
    totalMemory: number;
}

/**
 * Check if a given object implements the ClusterSizing interface.
 */
export function instanceOfClusterSizing(value: object): value is ClusterSizing {
    if (!('totalNodes' in value) || value['totalNodes'] === undefined) return false;
    if (!('workerNodes' in value) || value['workerNodes'] === undefined) return false;
    if (!('controlPlaneNodes' in value) || value['controlPlaneNodes'] === undefined) return false;
    if (!('totalCPU' in value) || value['totalCPU'] === undefined) return false;
    if (!('totalMemory' in value) || value['totalMemory'] === undefined) return false;
    return true;
}

export function ClusterSizingFromJSON(json: any): ClusterSizing {
    return ClusterSizingFromJSONTyped(json, false);
}

export function ClusterSizingFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClusterSizing {
    if (json == null) {
        return json;
    }
    return {
        
        'totalNodes': json['totalNodes'],
        'workerNodes': json['workerNodes'],
        'controlPlaneNodes': json['controlPlaneNodes'],
        'totalCPU': json['totalCPU'],
        'totalMemory': json['totalMemory'],
    };
}

export function ClusterSizingToJSON(json: any): ClusterSizing {
    return ClusterSizingToJSONTyped(json, false);
}

export function ClusterSizingToJSONTyped(value?: ClusterSizing | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'totalNodes': value['totalNodes'],
        'workerNodes': value['workerNodes'],
        'controlPlaneNodes': value['controlPlaneNodes'],
        'totalCPU': value['totalCPU'],
        'totalMemory': value['totalMemory'],
    };
}

