/* tslint:disable */
/* eslint-disable */
/**
 * Migration Planner API
 * Based on: https://github.com/kubev2v/migration-planner/blob/381e0e2f0d99c996a1230d27470988d7cbe9e282/api/v1alpha1/openapi.yaml
 *
 * The version of the OpenAPI document: 0.4.0-381e0e2f
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { SizingResourceConsumption } from './SizingResourceConsumption.js';
import {
    SizingResourceConsumptionFromJSON,
    SizingResourceConsumptionFromJSONTyped,
    SizingResourceConsumptionToJSON,
    SizingResourceConsumptionToJSONTyped,
} from './SizingResourceConsumption.js';
import type { InventoryTotals } from './InventoryTotals.js';
import {
    InventoryTotalsFromJSON,
    InventoryTotalsFromJSONTyped,
    InventoryTotalsToJSON,
    InventoryTotalsToJSONTyped,
} from './InventoryTotals.js';
import type { ClusterSizing } from './ClusterSizing.js';
import {
    ClusterSizingFromJSON,
    ClusterSizingFromJSONTyped,
    ClusterSizingToJSON,
    ClusterSizingToJSONTyped,
} from './ClusterSizing.js';

/**
 * Cluster requirements calculation results
 * @export
 * @interface ClusterRequirementsResponse
 */
export interface ClusterRequirementsResponse {
    /**
     * 
     * @type {ClusterSizing}
     * @memberof ClusterRequirementsResponse
     */
    clusterSizing: ClusterSizing;
    /**
     * 
     * @type {SizingResourceConsumption}
     * @memberof ClusterRequirementsResponse
     */
    resourceConsumption: SizingResourceConsumption;
    /**
     * 
     * @type {InventoryTotals}
     * @memberof ClusterRequirementsResponse
     */
    inventoryTotals: InventoryTotals;
}

/**
 * Check if a given object implements the ClusterRequirementsResponse interface.
 */
export function instanceOfClusterRequirementsResponse(value: object): value is ClusterRequirementsResponse {
    if (!('clusterSizing' in value) || value['clusterSizing'] === undefined) return false;
    if (!('resourceConsumption' in value) || value['resourceConsumption'] === undefined) return false;
    if (!('inventoryTotals' in value) || value['inventoryTotals'] === undefined) return false;
    return true;
}

export function ClusterRequirementsResponseFromJSON(json: any): ClusterRequirementsResponse {
    return ClusterRequirementsResponseFromJSONTyped(json, false);
}

export function ClusterRequirementsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClusterRequirementsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'clusterSizing': ClusterSizingFromJSON(json['clusterSizing']),
        'resourceConsumption': SizingResourceConsumptionFromJSON(json['resourceConsumption']),
        'inventoryTotals': InventoryTotalsFromJSON(json['inventoryTotals']),
    };
}

export function ClusterRequirementsResponseToJSON(json: any): ClusterRequirementsResponse {
    return ClusterRequirementsResponseToJSONTyped(json, false);
}

export function ClusterRequirementsResponseToJSONTyped(value?: ClusterRequirementsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'clusterSizing': ClusterSizingToJSON(value['clusterSizing']),
        'resourceConsumption': SizingResourceConsumptionToJSON(value['resourceConsumption']),
        'inventoryTotals': InventoryTotalsToJSON(value['inventoryTotals']),
    };
}

