/* tslint:disable */
/* eslint-disable */
/**
 * Migration Planner API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: undefined
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * Request payload for calculating cluster requirements
 * @export
 * @interface ClusterRequirementsRequest
 */
export interface ClusterRequirementsRequest {
    /**
     * ID of the cluster to calculate requirements for
     * @type {string}
     * @memberof ClusterRequirementsRequest
     */
    clusterId: string;
    /**
     * CPU over-commit ratio (e.g., "1:4")
     * @type {string}
     * @memberof ClusterRequirementsRequest
     */
    cpuOverCommitRatio: ClusterRequirementsRequestCpuOverCommitRatioEnum;
    /**
     * Memory over-commit ratio (e.g., "1:2")
     * @type {string}
     * @memberof ClusterRequirementsRequest
     */
    memoryOverCommitRatio: ClusterRequirementsRequestMemoryOverCommitRatioEnum;
    /**
     * CPU cores per worker node
     * @type {number}
     * @memberof ClusterRequirementsRequest
     */
    workerNodeCPU: number;
    /**
     * Memory (GB) per worker node
     * @type {number}
     * @memberof ClusterRequirementsRequest
     */
    workerNodeMemory: number;
    /**
     * Allow workload scheduling on control plane nodes
     * @type {boolean}
     * @memberof ClusterRequirementsRequest
     */
    controlPlaneSchedulable?: boolean;
}


/**
 * @export
 */
export const ClusterRequirementsRequestCpuOverCommitRatioEnum = {
    CpuOneToOne: '1:1',
    CpuOneToTwo: '1:2',
    CpuOneToFour: '1:4',
    CpuOneToSix: '1:6'
} as const;
export type ClusterRequirementsRequestCpuOverCommitRatioEnum = typeof ClusterRequirementsRequestCpuOverCommitRatioEnum[keyof typeof ClusterRequirementsRequestCpuOverCommitRatioEnum];

/**
 * @export
 */
export const ClusterRequirementsRequestMemoryOverCommitRatioEnum = {
    MemoryOneToOne: '1:1',
    MemoryOneToTwo: '1:2',
    MemoryOneToFour: '1:4'
} as const;
export type ClusterRequirementsRequestMemoryOverCommitRatioEnum = typeof ClusterRequirementsRequestMemoryOverCommitRatioEnum[keyof typeof ClusterRequirementsRequestMemoryOverCommitRatioEnum];


/**
 * Check if a given object implements the ClusterRequirementsRequest interface.
 */
export function instanceOfClusterRequirementsRequest(value: object): value is ClusterRequirementsRequest {
    if (!('clusterId' in value) || value['clusterId'] === undefined) return false;
    if (!('cpuOverCommitRatio' in value) || value['cpuOverCommitRatio'] === undefined) return false;
    if (!('memoryOverCommitRatio' in value) || value['memoryOverCommitRatio'] === undefined) return false;
    if (!('workerNodeCPU' in value) || value['workerNodeCPU'] === undefined) return false;
    if (!('workerNodeMemory' in value) || value['workerNodeMemory'] === undefined) return false;
    return true;
}

export function ClusterRequirementsRequestFromJSON(json: any): ClusterRequirementsRequest {
    return ClusterRequirementsRequestFromJSONTyped(json, false);
}

export function ClusterRequirementsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClusterRequirementsRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'clusterId': json['clusterId'],
        'cpuOverCommitRatio': json['cpuOverCommitRatio'],
        'memoryOverCommitRatio': json['memoryOverCommitRatio'],
        'workerNodeCPU': json['workerNodeCPU'],
        'workerNodeMemory': json['workerNodeMemory'],
        'controlPlaneSchedulable': json['controlPlaneSchedulable'] == null ? undefined : json['controlPlaneSchedulable'],
    };
}

export function ClusterRequirementsRequestToJSON(json: any): ClusterRequirementsRequest {
    return ClusterRequirementsRequestToJSONTyped(json, false);
}

export function ClusterRequirementsRequestToJSONTyped(value?: ClusterRequirementsRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'clusterId': value['clusterId'],
        'cpuOverCommitRatio': value['cpuOverCommitRatio'],
        'memoryOverCommitRatio': value['memoryOverCommitRatio'],
        'workerNodeCPU': value['workerNodeCPU'],
        'workerNodeMemory': value['workerNodeMemory'],
        'controlPlaneSchedulable': value['controlPlaneSchedulable'],
    };
}

