/* tslint:disable */
/* eslint-disable */
/**
 * Migration Planner API
 * Based on: https://github.com/kubev2v/migration-planner/blob/381e0e2f0d99c996a1230d27470988d7cbe9e282/api/v1alpha1/openapi.yaml
 *
 * The version of the OpenAPI document: 0.4.0-381e0e2f
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * Request payload for calculating cluster requirements
 * @export
 * @interface ClusterRequirementsRequest
 */
export interface ClusterRequirementsRequest {
    /**
     * ID of the cluster to calculate requirements for
     * @type {string}
     * @memberof ClusterRequirementsRequest
     */
    clusterId: string;
    /**
     * CPU over-commit ratio (e.g., "1:4")
     * @type {string}
     * @memberof ClusterRequirementsRequest
     */
    overCommitRatio: ClusterRequirementsRequestOverCommitRatioEnum;
    /**
     * CPU cores per worker node
     * @type {number}
     * @memberof ClusterRequirementsRequest
     */
    workerNodeCPU: number;
    /**
     * Memory (GB) per worker node
     * @type {number}
     * @memberof ClusterRequirementsRequest
     */
    workerNodeMemory: number;
    /**
     * Allow workload scheduling on control plane nodes
     * @type {boolean}
     * @memberof ClusterRequirementsRequest
     */
    controlPlaneSchedulable?: boolean;
}


/**
 * @export
 */
export const ClusterRequirementsRequestOverCommitRatioEnum = {
    OneToOne: '1:1',
    OneToTwo: '1:2',
    OneToFour: '1:4',
    OneToSix: '1:6'
} as const;
export type ClusterRequirementsRequestOverCommitRatioEnum = typeof ClusterRequirementsRequestOverCommitRatioEnum[keyof typeof ClusterRequirementsRequestOverCommitRatioEnum];


/**
 * Check if a given object implements the ClusterRequirementsRequest interface.
 */
export function instanceOfClusterRequirementsRequest(value: object): value is ClusterRequirementsRequest {
    if (!('clusterId' in value) || value['clusterId'] === undefined) return false;
    if (!('overCommitRatio' in value) || value['overCommitRatio'] === undefined) return false;
    if (!('workerNodeCPU' in value) || value['workerNodeCPU'] === undefined) return false;
    if (!('workerNodeMemory' in value) || value['workerNodeMemory'] === undefined) return false;
    return true;
}

export function ClusterRequirementsRequestFromJSON(json: any): ClusterRequirementsRequest {
    return ClusterRequirementsRequestFromJSONTyped(json, false);
}

export function ClusterRequirementsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClusterRequirementsRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'clusterId': json['clusterId'],
        'overCommitRatio': json['overCommitRatio'],
        'workerNodeCPU': json['workerNodeCPU'],
        'workerNodeMemory': json['workerNodeMemory'],
        'controlPlaneSchedulable': json['controlPlaneSchedulable'] == null ? undefined : json['controlPlaneSchedulable'],
    };
}

export function ClusterRequirementsRequestToJSON(json: any): ClusterRequirementsRequest {
    return ClusterRequirementsRequestToJSONTyped(json, false);
}

export function ClusterRequirementsRequestToJSONTyped(value?: ClusterRequirementsRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'clusterId': value['clusterId'],
        'overCommitRatio': value['overCommitRatio'],
        'workerNodeCPU': value['workerNodeCPU'],
        'workerNodeMemory': value['workerNodeMemory'],
        'controlPlaneSchedulable': value['controlPlaneSchedulable'],
    };
}

