/* tslint:disable */
/* eslint-disable */
/**
 * Migration Planner API
 * Based on: https://github.com/kubev2v/migration-planner/blob/e8c0ddb122bf87bd9fc79cba6e52d159a334f093/api/v1alpha1/openapi.yaml
 *
 * The version of the OpenAPI document: 0.4.0-e8c0ddb1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface DiskTypeSummary
 */
export interface DiskTypeSummary {
    /**
     * Number of VMs that have at least one disk of this type
     * @type {number}
     * @memberof DiskTypeSummary
     */
    vmCount: number;
    /**
     * Total disk size in TB for this disk type
     * @type {number}
     * @memberof DiskTypeSummary
     */
    totalSizeTB: number;
}

/**
 * Check if a given object implements the DiskTypeSummary interface.
 */
export function instanceOfDiskTypeSummary(value: object): value is DiskTypeSummary {
    if (!('vmCount' in value) || value['vmCount'] === undefined) return false;
    if (!('totalSizeTB' in value) || value['totalSizeTB'] === undefined) return false;
    return true;
}

export function DiskTypeSummaryFromJSON(json: any): DiskTypeSummary {
    return DiskTypeSummaryFromJSONTyped(json, false);
}

export function DiskTypeSummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): DiskTypeSummary {
    if (json == null) {
        return json;
    }
    return {
        
        'vmCount': json['vmCount'],
        'totalSizeTB': json['totalSizeTB'],
    };
}

export function DiskTypeSummaryToJSON(json: any): DiskTypeSummary {
    return DiskTypeSummaryToJSONTyped(json, false);
}

export function DiskTypeSummaryToJSONTyped(value?: DiskTypeSummary | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'vmCount': value['vmCount'],
        'totalSizeTB': value['totalSizeTB'],
    };
}

