/* tslint:disable */
/* eslint-disable */
/**
 * Migration Planner API
 * Based on: https://github.com/kubev2v/migration-planner/blob/bd435bf4e63611a5d609f7c918e85dd57830fccf/api/v1alpha1/openapi.yaml
 *
 * The version of the OpenAPI document: 0.4.0-bd435bf4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface DiskSizeTierSummary
 */
export interface DiskSizeTierSummary {
    /**
     * Total disk size in TB for this tier
     * @type {number}
     * @memberof DiskSizeTierSummary
     */
    totalSizeTB: number;
    /**
     * Number of VMs in this tier
     * @type {number}
     * @memberof DiskSizeTierSummary
     */
    vmCount: number;
}

/**
 * Check if a given object implements the DiskSizeTierSummary interface.
 */
export function instanceOfDiskSizeTierSummary(value: object): value is DiskSizeTierSummary {
    if (!('totalSizeTB' in value) || value['totalSizeTB'] === undefined) return false;
    if (!('vmCount' in value) || value['vmCount'] === undefined) return false;
    return true;
}

export function DiskSizeTierSummaryFromJSON(json: any): DiskSizeTierSummary {
    return DiskSizeTierSummaryFromJSONTyped(json, false);
}

export function DiskSizeTierSummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): DiskSizeTierSummary {
    if (json == null) {
        return json;
    }
    return {
        
        'totalSizeTB': json['totalSizeTB'],
        'vmCount': json['vmCount'],
    };
}

export function DiskSizeTierSummaryToJSON(json: any): DiskSizeTierSummary {
    return DiskSizeTierSummaryToJSONTyped(json, false);
}

export function DiskSizeTierSummaryToJSONTyped(value?: DiskSizeTierSummary | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'totalSizeTB': value['totalSizeTB'],
        'vmCount': value['vmCount'],
    };
}

