/* tslint:disable */
/* eslint-disable */
/**
 * Migration Planner API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: undefined
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DiskTypeSummary
 */
export interface DiskTypeSummary {
    /**
     * Number of VMs that have at least one disk of this type
     * @type {number}
     * @memberof DiskTypeSummary
     */
    vmCount: number;
    /**
     * Total disk size in TB for this disk type
     * @type {number}
     * @memberof DiskTypeSummary
     */
    totalSizeTB: number;
}

/**
 * Check if a given object implements the DiskTypeSummary interface.
 */
export function instanceOfDiskTypeSummary(value: object): value is DiskTypeSummary {
    if (!('vmCount' in value) || value['vmCount'] === undefined) return false;
    if (!('totalSizeTB' in value) || value['totalSizeTB'] === undefined) return false;
    return true;
}

export function DiskTypeSummaryFromJSON(json: any): DiskTypeSummary {
    return DiskTypeSummaryFromJSONTyped(json, false);
}

export function DiskTypeSummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): DiskTypeSummary {
    if (json == null) {
        return json;
    }
    return {
        
        'vmCount': json['vmCount'],
        'totalSizeTB': json['totalSizeTB'],
    };
}

export function DiskTypeSummaryToJSON(value?: DiskTypeSummary | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'vmCount': value['vmCount'],
        'totalSizeTB': value['totalSizeTB'],
    };
}

