/* tslint:disable */
/* eslint-disable */
/**
 * Migration Planner API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: undefined
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EventData
 */
export interface EventData {
    /**
     * 
     * @type {string}
     * @memberof EventData
     */
    key: string;
    /**
     * 
     * @type {string}
     * @memberof EventData
     */
    value: string;
}

/**
 * Check if a given object implements the EventData interface.
 */
export function instanceOfEventData(value: object): value is EventData {
    if (!('key' in value) || value['key'] === undefined) return false;
    if (!('value' in value) || value['value'] === undefined) return false;
    return true;
}

export function EventDataFromJSON(json: any): EventData {
    return EventDataFromJSONTyped(json, false);
}

export function EventDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): EventData {
    if (json == null) {
        return json;
    }
    return {
        
        'key': json['key'],
        'value': json['value'],
    };
}

export function EventDataToJSON(value?: EventData | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'key': value['key'],
        'value': value['value'],
    };
}

