/* tslint:disable */
/* eslint-disable */
/**
 * Migration Planner API
 * Based on: https://github.com/kubev2v/migration-planner/blob/bd435bf4e63611a5d609f7c918e85dd57830fccf/api/v1alpha1/openapi.yaml
 *
 * The version of the OpenAPI document: 0.4.0-bd435bf4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface Histogram
 */
export interface Histogram {
    /**
     * 
     * @type {number}
     * @memberof Histogram
     */
    minValue: number;
    /**
     * 
     * @type {number}
     * @memberof Histogram
     */
    step: number;
    /**
     * 
     * @type {Array<number>}
     * @memberof Histogram
     */
    data: Array<number>;
}

/**
 * Check if a given object implements the Histogram interface.
 */
export function instanceOfHistogram(value: object): value is Histogram {
    if (!('minValue' in value) || value['minValue'] === undefined) return false;
    if (!('step' in value) || value['step'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function HistogramFromJSON(json: any): Histogram {
    return HistogramFromJSONTyped(json, false);
}

export function HistogramFromJSONTyped(json: any, ignoreDiscriminator: boolean): Histogram {
    if (json == null) {
        return json;
    }
    return {
        
        'minValue': json['minValue'],
        'step': json['step'],
        'data': json['data'],
    };
}

export function HistogramToJSON(json: any): Histogram {
    return HistogramToJSONTyped(json, false);
}

export function HistogramToJSONTyped(value?: Histogram | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'minValue': value['minValue'],
        'step': value['step'],
        'data': value['data'],
    };
}

