/* tslint:disable */
/* eslint-disable */
/**
 * Migration Planner API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: undefined
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Host
 */
export interface Host {
    /**
     * 
     * @type {string}
     * @memberof Host
     */
    vendor: string;
    /**
     * 
     * @type {string}
     * @memberof Host
     */
    model: string;
}

/**
 * Check if a given object implements the Host interface.
 */
export function instanceOfHost(value: object): value is Host {
    if (!('vendor' in value) || value['vendor'] === undefined) return false;
    if (!('model' in value) || value['model'] === undefined) return false;
    return true;
}

export function HostFromJSON(json: any): Host {
    return HostFromJSONTyped(json, false);
}

export function HostFromJSONTyped(json: any, ignoreDiscriminator: boolean): Host {
    if (json == null) {
        return json;
    }
    return {
        
        'vendor': json['vendor'],
        'model': json['model'],
    };
}

export function HostToJSON(value?: Host | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'vendor': value['vendor'],
        'model': value['model'],
    };
}

