/* tslint:disable */
/* eslint-disable */
/**
 * Migration Planner API
 * Based on: https://github.com/kubev2v/migration-planner/blob/e8c0ddb122bf87bd9fc79cba6e52d159a334f093/api/v1alpha1/openapi.yaml
 *
 * The version of the OpenAPI document: 0.4.0-e8c0ddb1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * Migration planner information
 * @export
 * @interface Info
 */
export interface Info {
    /**
     * Git commit hash
     * @type {string}
     * @memberof Info
     */
    gitCommit: string;
    /**
     * Version name, based on git tag
     * @type {string}
     * @memberof Info
     */
    versionName: string;
}

/**
 * Check if a given object implements the Info interface.
 */
export function instanceOfInfo(value: object): value is Info {
    if (!('gitCommit' in value) || value['gitCommit'] === undefined) return false;
    if (!('versionName' in value) || value['versionName'] === undefined) return false;
    return true;
}

export function InfoFromJSON(json: any): Info {
    return InfoFromJSONTyped(json, false);
}

export function InfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): Info {
    if (json == null) {
        return json;
    }
    return {
        
        'gitCommit': json['gitCommit'],
        'versionName': json['versionName'],
    };
}

export function InfoToJSON(json: any): Info {
    return InfoToJSONTyped(json, false);
}

export function InfoToJSONTyped(value?: Info | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'gitCommit': value['gitCommit'],
        'versionName': value['versionName'],
    };
}

