/* tslint:disable */
/* eslint-disable */
/**
 * Migration Planner API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: undefined
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Datastore } from './Datastore';
import {
    DatastoreFromJSON,
    DatastoreFromJSONTyped,
    DatastoreToJSON,
} from './Datastore';
import type { Network } from './Network';
import {
    NetworkFromJSON,
    NetworkFromJSONTyped,
    NetworkToJSON,
} from './Network';
import type { Host } from './Host';
import {
    HostFromJSON,
    HostFromJSONTyped,
    HostToJSON,
} from './Host';

/**
 * 
 * @export
 * @interface Infra
 */
export interface Infra {
    /**
     * 
     * @type {number}
     * @memberof Infra
     */
    totalHosts: number;
    /**
     * 
     * @type {number}
     * @memberof Infra
     */
    totalDatacenters: number;
    /**
     * 
     * @type {number}
     * @memberof Infra
     */
    totalClusters: number;
    /**
     * 
     * @type {Array<number>}
     * @memberof Infra
     */
    clustersPerDatacenter: Array<number>;
    /**
     * 
     * @type {Array<Host>}
     * @memberof Infra
     */
    hosts: Array<Host>;
    /**
     * 
     * @type {Array<number>}
     * @memberof Infra
     */
    hostsPerCluster: Array<number>;
    /**
     * 
     * @type {{ [key: string]: number; }}
     * @memberof Infra
     */
    hostPowerStates: { [key: string]: number; };
    /**
     * 
     * @type {Array<Network>}
     * @memberof Infra
     */
    networks: Array<Network>;
    /**
     * 
     * @type {Array<Datastore>}
     * @memberof Infra
     */
    datastores: Array<Datastore>;
}

/**
 * Check if a given object implements the Infra interface.
 */
export function instanceOfInfra(value: object): value is Infra {
    if (!('totalHosts' in value) || value['totalHosts'] === undefined) return false;
    if (!('totalDatacenters' in value) || value['totalDatacenters'] === undefined) return false;
    if (!('totalClusters' in value) || value['totalClusters'] === undefined) return false;
    if (!('clustersPerDatacenter' in value) || value['clustersPerDatacenter'] === undefined) return false;
    if (!('hosts' in value) || value['hosts'] === undefined) return false;
    if (!('hostsPerCluster' in value) || value['hostsPerCluster'] === undefined) return false;
    if (!('hostPowerStates' in value) || value['hostPowerStates'] === undefined) return false;
    if (!('networks' in value) || value['networks'] === undefined) return false;
    if (!('datastores' in value) || value['datastores'] === undefined) return false;
    return true;
}

export function InfraFromJSON(json: any): Infra {
    return InfraFromJSONTyped(json, false);
}

export function InfraFromJSONTyped(json: any, ignoreDiscriminator: boolean): Infra {
    if (json == null) {
        return json;
    }
    return {
        
        'totalHosts': json['totalHosts'] || 0,
        'totalDatacenters': json['totalDatacenters'] || 0,
        'totalClusters': json['totalClusters'] || 0,
        'clustersPerDatacenter': json['clustersPerDatacenter'] || [],
        'hosts': ((json['hosts'] as Array<any>) || []).map(HostFromJSON),
        'hostsPerCluster': json['hostsPerCluster'] || [],
        'hostPowerStates': json['hostPowerStates'] || {},
        'networks': ((json['networks'] as Array<any>) || []).map(NetworkFromJSON),
        'datastores': ((json['datastores'] as Array<any>) || []).map(DatastoreFromJSON),
    };
}

export function InfraToJSON(value?: Infra | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'totalHosts': value['totalHosts'],
        'totalDatacenters': value['totalDatacenters'],
        'totalClusters': value['totalClusters'],
        'clustersPerDatacenter': value['clustersPerDatacenter'],
        'hosts': ((value['hosts'] as Array<any>).map(HostToJSON)),
        'hostsPerCluster': value['hostsPerCluster'],
        'hostPowerStates': value['hostPowerStates'],
        'networks': ((value['networks'] as Array<any>).map(NetworkToJSON)),
        'datastores': ((value['datastores'] as Array<any>).map(DatastoreToJSON)),
    };
}

