/* tslint:disable */
/* eslint-disable */
/**
 * Migration Planner API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: undefined
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InfraDatastoresInner
 */
export interface InfraDatastoresInner {
    /**
     * 
     * @type {string}
     * @memberof InfraDatastoresInner
     */
    type: string;
    /**
     * 
     * @type {number}
     * @memberof InfraDatastoresInner
     */
    totalCapacityGB: number;
    /**
     * 
     * @type {number}
     * @memberof InfraDatastoresInner
     */
    freeCapacityGB: number;
}

/**
 * Check if a given object implements the InfraDatastoresInner interface.
 */
export function instanceOfInfraDatastoresInner(value: object): value is InfraDatastoresInner {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('totalCapacityGB' in value) || value['totalCapacityGB'] === undefined) return false;
    if (!('freeCapacityGB' in value) || value['freeCapacityGB'] === undefined) return false;
    return true;
}

export function InfraDatastoresInnerFromJSON(json: any): InfraDatastoresInner {
    return InfraDatastoresInnerFromJSONTyped(json, false);
}

export function InfraDatastoresInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): InfraDatastoresInner {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'totalCapacityGB': json['totalCapacityGB'],
        'freeCapacityGB': json['freeCapacityGB'],
    };
}

export function InfraDatastoresInnerToJSON(value?: InfraDatastoresInner | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'type': value['type'],
        'totalCapacityGB': value['totalCapacityGB'],
        'freeCapacityGB': value['freeCapacityGB'],
    };
}

