/* tslint:disable */
/* eslint-disable */
/**
 * Migration Planner API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: undefined
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { VCenter } from './VCenter';
import {
    VCenterFromJSON,
    VCenterFromJSONTyped,
    VCenterToJSON,
} from './VCenter';
import type { Infra } from './Infra';
import {
    InfraFromJSON,
    InfraFromJSONTyped,
    InfraToJSON,
} from './Infra';
import type { VMs } from './VMs';
import {
    VMsFromJSON,
    VMsFromJSONTyped,
    VMsToJSON,
} from './VMs';

/**
 * 
 * @export
 * @interface Inventory
 */
export interface Inventory {
    /**
     * 
     * @type {VCenter}
     * @memberof Inventory
     */
    vcenter: VCenter;
    /**
     * 
     * @type {VMs}
     * @memberof Inventory
     */
    vms: VMs;
    /**
     * 
     * @type {Infra}
     * @memberof Inventory
     */
    infra: Infra;
}

/**
 * Check if a given object implements the Inventory interface.
 */
export function instanceOfInventory(value: object): value is Inventory {
    if (!('vcenter' in value) || value['vcenter'] === undefined) return false;
    if (!('vms' in value) || value['vms'] === undefined) return false;
    if (!('infra' in value) || value['infra'] === undefined) return false;
    return true;
}

export function InventoryFromJSON(json: any): Inventory {
    return InventoryFromJSONTyped(json, false);
}

export function InventoryFromJSONTyped(json: any, ignoreDiscriminator: boolean): Inventory {
    if (json == null) {
        return json;
    }
    return {
        
        'vcenter': json['vcenter'],
        'vms': json['vms'],
        'infra': json['infra'],
    };
}

export function InventoryToJSON(value?: Inventory | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'vcenter': value['vcenter'],
        'vms': value['vms'],
        'infra': value['infra'],
    };
}

