/* tslint:disable */
/* eslint-disable */
/**
 * Migration Planner API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: undefined
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { VCenter } from './VCenter';
import {
    VCenterFromJSON,
    VCenterFromJSONTyped,
    VCenterToJSON,
} from './VCenter';
import type { Infra } from './Infra';
import {
    InfraFromJSON,
    InfraFromJSONTyped,
    InfraToJSON,
} from './Infra';
import type { VMs } from './VMs';
import {
    VMsFromJSON,
    VMsFromJSONTyped,
    VMsToJSON,
} from './VMs';

/**
 * 
 * @export
 * @interface InventoryData
 */
export interface InventoryData {
    /**
     * 
     * @type {VCenter}
     * @memberof InventoryData
     */
    vcenter?: VCenter;
    /**
     * 
     * @type {VMs}
     * @memberof InventoryData
     */
    vms: VMs;
    /**
     * 
     * @type {Infra}
     * @memberof InventoryData
     */
    infra: Infra;
}

/**
 * Check if a given object implements the InventoryData interface.
 */
export function instanceOfInventoryData(value: object): value is InventoryData {
    if (!('vms' in value) || value['vms'] === undefined) return false;
    if (!('infra' in value) || value['infra'] === undefined) return false;
    return true;
}

export function InventoryDataFromJSON(json: any): InventoryData {
    return InventoryDataFromJSONTyped(json, false);
}

export function InventoryDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): InventoryData {
    if (json == null) {
        return json;
    }
    return {
        
        'vcenter': json['vcenter'] == null ? undefined : VCenterFromJSON(json['vcenter']),
        'vms': VMsFromJSON(json['vms']),
        'infra': InfraFromJSON(json['infra']),
    };
}

export function InventoryDataToJSON(value?: InventoryData | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'vcenter': VCenterToJSON(value['vcenter']),
        'vms': VMsToJSON(value['vms']),
        'infra': InfraToJSON(value['infra']),
    };
}

