/* tslint:disable */
/* eslint-disable */
/**
 * Migration Planner API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: undefined
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * Inventory totals for the cluster
 * @export
 * @interface InventoryTotals
 */
export interface InventoryTotals {
    /**
     * Total number of VMs in the cluster
     * @type {number}
     * @memberof InventoryTotals
     */
    totalVMs: number;
    /**
     * Total CPU cores across all VMs in the cluster
     * @type {number}
     * @memberof InventoryTotals
     */
    totalCPU: number;
    /**
     * Total memory (GB) across all VMs in the cluster
     * @type {number}
     * @memberof InventoryTotals
     */
    totalMemory: number;
}

/**
 * Check if a given object implements the InventoryTotals interface.
 */
export function instanceOfInventoryTotals(value: object): value is InventoryTotals {
    if (!('totalVMs' in value) || value['totalVMs'] === undefined) return false;
    if (!('totalCPU' in value) || value['totalCPU'] === undefined) return false;
    if (!('totalMemory' in value) || value['totalMemory'] === undefined) return false;
    return true;
}

export function InventoryTotalsFromJSON(json: any): InventoryTotals {
    return InventoryTotalsFromJSONTyped(json, false);
}

export function InventoryTotalsFromJSONTyped(json: any, ignoreDiscriminator: boolean): InventoryTotals {
    if (json == null) {
        return json;
    }
    return {
        
        'totalVMs': json['totalVMs'],
        'totalCPU': json['totalCPU'],
        'totalMemory': json['totalMemory'],
    };
}

export function InventoryTotalsToJSON(json: any): InventoryTotals {
    return InventoryTotalsToJSONTyped(json, false);
}

export function InventoryTotalsToJSONTyped(value?: InventoryTotals | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'totalVMs': value['totalVMs'],
        'totalCPU': value['totalCPU'],
        'totalMemory': value['totalMemory'],
    };
}

