/* tslint:disable */
/* eslint-disable */
/**
 * Migration Planner API
 * Based on: https://github.com/kubev2v/migration-planner/blob/e8c0ddb122bf87bd9fc79cba6e52d159a334f093/api/v1alpha1/openapi.yaml
 *
 * The version of the OpenAPI document: 0.4.0-e8c0ddb1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface Ipv4Config
 */
export interface Ipv4Config {
    /**
     * 
     * @type {string}
     * @memberof Ipv4Config
     */
    ipAddress: string;
    /**
     * 
     * @type {string}
     * @memberof Ipv4Config
     */
    subnetMask: string;
    /**
     * 
     * @type {string}
     * @memberof Ipv4Config
     */
    defaultGateway: string;
    /**
     * 
     * @type {string}
     * @memberof Ipv4Config
     */
    dns: string;
}

/**
 * Check if a given object implements the Ipv4Config interface.
 */
export function instanceOfIpv4Config(value: object): value is Ipv4Config {
    if (!('ipAddress' in value) || value['ipAddress'] === undefined) return false;
    if (!('subnetMask' in value) || value['subnetMask'] === undefined) return false;
    if (!('defaultGateway' in value) || value['defaultGateway'] === undefined) return false;
    if (!('dns' in value) || value['dns'] === undefined) return false;
    return true;
}

export function Ipv4ConfigFromJSON(json: any): Ipv4Config {
    return Ipv4ConfigFromJSONTyped(json, false);
}

export function Ipv4ConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): Ipv4Config {
    if (json == null) {
        return json;
    }
    return {
        
        'ipAddress': json['ipAddress'],
        'subnetMask': json['subnetMask'],
        'defaultGateway': json['defaultGateway'],
        'dns': json['dns'],
    };
}

export function Ipv4ConfigToJSON(json: any): Ipv4Config {
    return Ipv4ConfigToJSONTyped(json, false);
}

export function Ipv4ConfigToJSONTyped(value?: Ipv4Config | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ipAddress': value['ipAddress'],
        'subnetMask': value['subnetMask'],
        'defaultGateway': value['defaultGateway'],
        'dns': value['dns'],
    };
}

