/* tslint:disable */
/* eslint-disable */
/**
 * Migration Planner API
 * Based on: https://github.com/kubev2v/migration-planner/blob/e8c0ddb122bf87bd9fc79cba6e52d159a334f093/api/v1alpha1/openapi.yaml
 *
 * The version of the OpenAPI document: 0.4.0-e8c0ddb1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface Label
 */
export interface Label {
    /**
     * 
     * @type {string}
     * @memberof Label
     */
    key: string;
    /**
     * 
     * @type {string}
     * @memberof Label
     */
    value: string;
}

/**
 * Check if a given object implements the Label interface.
 */
export function instanceOfLabel(value: object): value is Label {
    if (!('key' in value) || value['key'] === undefined) return false;
    if (!('value' in value) || value['value'] === undefined) return false;
    return true;
}

export function LabelFromJSON(json: any): Label {
    return LabelFromJSONTyped(json, false);
}

export function LabelFromJSONTyped(json: any, ignoreDiscriminator: boolean): Label {
    if (json == null) {
        return json;
    }
    return {
        
        'key': json['key'],
        'value': json['value'],
    };
}

export function LabelToJSON(json: any): Label {
    return LabelToJSONTyped(json, false);
}

export function LabelToJSONTyped(value?: Label | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'key': value['key'],
        'value': value['value'],
    };
}

