/* tslint:disable */
/* eslint-disable */
/**
 * Migration Planner API
 * Based on: https://github.com/kubev2v/migration-planner/blob/381e0e2f0d99c996a1230d27470988d7cbe9e282/api/v1alpha1/openapi.yaml
 *
 * The version of the OpenAPI document: 0.4.0-381e0e2f
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface MigrationIssue
 */
export interface MigrationIssue {
    /**
     * 
     * @type {string}
     * @memberof MigrationIssue
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof MigrationIssue
     */
    label: string;
    /**
     * 
     * @type {string}
     * @memberof MigrationIssue
     */
    assessment: string;
    /**
     * 
     * @type {number}
     * @memberof MigrationIssue
     */
    count: number;
}

/**
 * Check if a given object implements the MigrationIssue interface.
 */
export function instanceOfMigrationIssue(value: object): value is MigrationIssue {
    if (!('label' in value) || value['label'] === undefined) return false;
    if (!('assessment' in value) || value['assessment'] === undefined) return false;
    if (!('count' in value) || value['count'] === undefined) return false;
    return true;
}

export function MigrationIssueFromJSON(json: any): MigrationIssue {
    return MigrationIssueFromJSONTyped(json, false);
}

export function MigrationIssueFromJSONTyped(json: any, ignoreDiscriminator: boolean): MigrationIssue {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'label': json['label'],
        'assessment': json['assessment'],
        'count': json['count'],
    };
}

export function MigrationIssueToJSON(json: any): MigrationIssue {
    return MigrationIssueToJSONTyped(json, false);
}

export function MigrationIssueToJSONTyped(value?: MigrationIssue | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'label': value['label'],
        'assessment': value['assessment'],
        'count': value['count'],
    };
}

