/* tslint:disable */
/* eslint-disable */
/**
 * Migration Planner API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: undefined
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Network
 */
export interface Network {
    /**
     * 
     * @type {string}
     * @memberof Network
     */
    type: NetworkTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof Network
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof Network
     */
    vlanId?: string;
    /**
     * 
     * @type {string}
     * @memberof Network
     */
    dvswitch?: string;
}


/**
 * @export
 */
export const NetworkTypeEnum = {
    Standard: 'standard',
    Distributed: 'distributed',
    Dvswitch: 'dvswitch',
    Unsupported: 'unsupported'
} as const;
export type NetworkTypeEnum = typeof NetworkTypeEnum[keyof typeof NetworkTypeEnum];


/**
 * Check if a given object implements the Network interface.
 */
export function instanceOfNetwork(value: object): value is Network {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function NetworkFromJSON(json: any): Network {
    return NetworkFromJSONTyped(json, false);
}

export function NetworkFromJSONTyped(json: any, ignoreDiscriminator: boolean): Network {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'name': json['name'],
        'vlanId': json['vlanId'] == null ? undefined : json['vlanId'],
        'dvswitch': json['dvswitch'] == null ? undefined : json['dvswitch'],
    };
}

export function NetworkToJSON(value?: Network | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'type': value['type'],
        'name': value['name'],
        'vlanId': value['vlanId'],
        'dvswitch': value['dvswitch'],
    };
}

