/* tslint:disable */
/* eslint-disable */
/**
 * Migration Planner API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: undefined
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OsInfo
 */
export interface OsInfo {
    /**
     * 
     * @type {number}
     * @memberof OsInfo
     */
    count: number;
    /**
     * 
     * @type {boolean}
     * @memberof OsInfo
     */
    supported: boolean;
    /**
     * Recommended OS upgrade for MTV unsupported OS that can be upgraded to a supported OS
     * @type {string}
     * @memberof OsInfo
     */
    upgradeRecommendation?: string;
}

/**
 * Check if a given object implements the OsInfo interface.
 */
export function instanceOfOsInfo(value: object): value is OsInfo {
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('supported' in value) || value['supported'] === undefined) return false;
    return true;
}

export function OsInfoFromJSON(json: any): OsInfo {
    return OsInfoFromJSONTyped(json, false);
}

export function OsInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): OsInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
        'supported': json['supported'],
        'upgradeRecommendation': json['upgradeRecommendation'] == null ? undefined : json['upgradeRecommendation'],
    };
}

export function OsInfoToJSON(value?: OsInfo | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'count': value['count'],
        'supported': value['supported'],
        'upgradeRecommendation': value['upgradeRecommendation'],
    };
}

