/* tslint:disable */
/* eslint-disable */
/**
 * Migration Planner API
 * Based on: https://github.com/kubev2v/migration-planner/blob/381e0e2f0d99c996a1230d27470988d7cbe9e282/api/v1alpha1/openapi.yaml
 *
 * The version of the OpenAPI document: 0.4.0-381e0e2f
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { SizingOverCommitRatio } from './SizingOverCommitRatio.js';
import {
    SizingOverCommitRatioFromJSON,
    SizingOverCommitRatioFromJSONTyped,
    SizingOverCommitRatioToJSON,
    SizingOverCommitRatioToJSONTyped,
} from './SizingOverCommitRatio.js';
import type { SizingResourceLimits } from './SizingResourceLimits.js';
import {
    SizingResourceLimitsFromJSON,
    SizingResourceLimitsFromJSONTyped,
    SizingResourceLimitsToJSON,
    SizingResourceLimitsToJSONTyped,
} from './SizingResourceLimits.js';

/**
 * Resource consumption across the cluster
 * @export
 * @interface SizingResourceConsumption
 */
export interface SizingResourceConsumption {
    /**
     * Total CPU requested
     * @type {number}
     * @memberof SizingResourceConsumption
     */
    cpu: number;
    /**
     * Total memory (GB) requested
     * @type {number}
     * @memberof SizingResourceConsumption
     */
    memory: number;
    /**
     * 
     * @type {SizingResourceLimits}
     * @memberof SizingResourceConsumption
     */
    limits?: SizingResourceLimits;
    /**
     * 
     * @type {SizingOverCommitRatio}
     * @memberof SizingResourceConsumption
     */
    overCommitRatio?: SizingOverCommitRatio;
}

/**
 * Check if a given object implements the SizingResourceConsumption interface.
 */
export function instanceOfSizingResourceConsumption(value: object): value is SizingResourceConsumption {
    if (!('cpu' in value) || value['cpu'] === undefined) return false;
    if (!('memory' in value) || value['memory'] === undefined) return false;
    return true;
}

export function SizingResourceConsumptionFromJSON(json: any): SizingResourceConsumption {
    return SizingResourceConsumptionFromJSONTyped(json, false);
}

export function SizingResourceConsumptionFromJSONTyped(json: any, ignoreDiscriminator: boolean): SizingResourceConsumption {
    if (json == null) {
        return json;
    }
    return {
        
        'cpu': json['cpu'],
        'memory': json['memory'],
        'limits': json['limits'] == null ? undefined : SizingResourceLimitsFromJSON(json['limits']),
        'overCommitRatio': json['overCommitRatio'] == null ? undefined : SizingOverCommitRatioFromJSON(json['overCommitRatio']),
    };
}

export function SizingResourceConsumptionToJSON(json: any): SizingResourceConsumption {
    return SizingResourceConsumptionToJSONTyped(json, false);
}

export function SizingResourceConsumptionToJSONTyped(value?: SizingResourceConsumption | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'cpu': value['cpu'],
        'memory': value['memory'],
        'limits': SizingResourceLimitsToJSON(value['limits']),
        'overCommitRatio': SizingOverCommitRatioToJSON(value['overCommitRatio']),
    };
}

