/* tslint:disable */
/* eslint-disable */
/**
 * Migration Planner API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: undefined
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * Over-commit ratios
 * @export
 * @interface SizingOverCommitRatio
 */
export interface SizingOverCommitRatio {
    /**
     * CPU over-commit ratio
     * @type {number}
     * @memberof SizingOverCommitRatio
     */
    cpu: number;
    /**
     * Memory over-commit ratio
     * @type {number}
     * @memberof SizingOverCommitRatio
     */
    memory: number;
}

/**
 * Check if a given object implements the SizingOverCommitRatio interface.
 */
export function instanceOfSizingOverCommitRatio(value: object): value is SizingOverCommitRatio {
    if (!('cpu' in value) || value['cpu'] === undefined) return false;
    if (!('memory' in value) || value['memory'] === undefined) return false;
    return true;
}

export function SizingOverCommitRatioFromJSON(json: any): SizingOverCommitRatio {
    return SizingOverCommitRatioFromJSONTyped(json, false);
}

export function SizingOverCommitRatioFromJSONTyped(json: any, ignoreDiscriminator: boolean): SizingOverCommitRatio {
    if (json == null) {
        return json;
    }
    return {
        
        'cpu': json['cpu'],
        'memory': json['memory'],
    };
}

export function SizingOverCommitRatioToJSON(json: any): SizingOverCommitRatio {
    return SizingOverCommitRatioToJSONTyped(json, false);
}

export function SizingOverCommitRatioToJSONTyped(value?: SizingOverCommitRatio | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'cpu': value['cpu'],
        'memory': value['memory'],
    };
}

