/* tslint:disable */
/* eslint-disable */
/**
 * Migration Planner API
 * Based on: https://github.com/kubev2v/migration-planner/blob/381e0e2f0d99c996a1230d27470988d7cbe9e282/api/v1alpha1/openapi.yaml
 *
 * The version of the OpenAPI document: 0.4.0-381e0e2f
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * Resource limits
 * @export
 * @interface SizingResourceLimits
 */
export interface SizingResourceLimits {
    /**
     * Total CPU limits
     * @type {number}
     * @memberof SizingResourceLimits
     */
    cpu: number;
    /**
     * Total memory (GB) limits
     * @type {number}
     * @memberof SizingResourceLimits
     */
    memory: number;
}

/**
 * Check if a given object implements the SizingResourceLimits interface.
 */
export function instanceOfSizingResourceLimits(value: object): value is SizingResourceLimits {
    if (!('cpu' in value) || value['cpu'] === undefined) return false;
    if (!('memory' in value) || value['memory'] === undefined) return false;
    return true;
}

export function SizingResourceLimitsFromJSON(json: any): SizingResourceLimits {
    return SizingResourceLimitsFromJSONTyped(json, false);
}

export function SizingResourceLimitsFromJSONTyped(json: any, ignoreDiscriminator: boolean): SizingResourceLimits {
    if (json == null) {
        return json;
    }
    return {
        
        'cpu': json['cpu'],
        'memory': json['memory'],
    };
}

export function SizingResourceLimitsToJSON(json: any): SizingResourceLimits {
    return SizingResourceLimitsToJSONTyped(json, false);
}

export function SizingResourceLimitsToJSONTyped(value?: SizingResourceLimits | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'cpu': value['cpu'],
        'memory': value['memory'],
    };
}

