/* tslint:disable */
/* eslint-disable */
/**
 * Migration Planner API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: undefined
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Inventory } from './Inventory';
import {
    InventoryFromJSON,
    InventoryFromJSONTyped,
    InventoryToJSON,
} from './Inventory';

/**
 * 
 * @export
 * @interface Snapshot
 */
export interface Snapshot {
    /**
     * 
     * @type {Date}
     * @memberof Snapshot
     */
    createdAt: Date;
    /**
     * Status of the snapshot processing
     * @type {string}
     * @memberof Snapshot
     */
    status: SnapshotStatusEnum;
    /**
     * Error message if snapshot processing failed
     * @type {string}
     * @memberof Snapshot
     */
    error?: string;
    /**
     * 
     * @type {Inventory}
     * @memberof Snapshot
     */
    inventory?: Inventory;
}


/**
 * @export
 */
export const SnapshotStatusEnum = {
    Pending: 'pending',
    Parsing: 'parsing',
    Validating: 'validating',
    Ready: 'ready',
    Failed: 'failed'
} as const;
export type SnapshotStatusEnum = typeof SnapshotStatusEnum[keyof typeof SnapshotStatusEnum];


/**
 * Check if a given object implements the Snapshot interface.
 */
export function instanceOfSnapshot(value: object): value is Snapshot {
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function SnapshotFromJSON(json: any): Snapshot {
    return SnapshotFromJSONTyped(json, false);
}

export function SnapshotFromJSONTyped(json: any, ignoreDiscriminator: boolean): Snapshot {
    if (json == null) {
        return json;
    }
    return {
        
        'createdAt': (new Date(json['createdAt'])),
        'status': json['status'],
        'error': json['error'] == null ? undefined : json['error'],
        'inventory': json['inventory'] == null ? undefined : InventoryFromJSON(json['inventory']),
    };
}

export function SnapshotToJSON(value?: Snapshot | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'createdAt': ((value['createdAt']).toISOString()),
        'status': value['status'],
        'error': value['error'],
        'inventory': InventoryToJSON(value['inventory']),
    };
}

