/* tslint:disable */
/* eslint-disable */
/**
 * Migration Planner API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: undefined
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { Inventory } from './Inventory';
import {
    InventoryFromJSON,
    InventoryToJSON,
} from './Inventory';

/**
 * 
 * @export
 * @interface Snapshot
 */
export interface Snapshot {
    /**
     * 
     * @type {Inventory}
     * @memberof Snapshot
     */
    inventory: Inventory;
    /**
     * 
     * @type {Date}
     * @memberof Snapshot
     */
    createdAt: Date;
}

/**
 * Check if a given object implements the Snapshot interface.
 */
export function instanceOfSnapshot(value: object): value is Snapshot {
    if (!('inventory' in value) || value['inventory'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function SnapshotFromJSON(json: any): Snapshot {
    return SnapshotFromJSONTyped(json, false);
}

export function SnapshotFromJSONTyped(json: any, ignoreDiscriminator: boolean): Snapshot {
    if (json == null) {
        return json;
    }
    return {
        
        'inventory': InventoryFromJSON(json['inventory']),
        'createdAt': (new Date(json['createdAt'])),
    };
}

export function SnapshotToJSON(value?: Snapshot | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'inventory': InventoryToJSON(value['inventory']),
        'createdAt': ((value['createdAt']).toISOString()),
    };
}

