/* tslint:disable */
/* eslint-disable */
/**
 * Migration Planner API
 * Based on: https://github.com/kubev2v/migration-planner/blob/381e0e2f0d99c996a1230d27470988d7cbe9e282/api/v1alpha1/openapi.yaml
 *
 * The version of the OpenAPI document: 0.4.0-381e0e2f
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { Inventory } from './Inventory.js';
import {
    InventoryFromJSON,
    InventoryFromJSONTyped,
    InventoryToJSON,
    InventoryToJSONTyped,
} from './Inventory.js';

/**
 * 
 * @export
 * @interface Snapshot
 */
export interface Snapshot {
    /**
     * 
     * @type {Inventory}
     * @memberof Snapshot
     */
    inventory: Inventory;
    /**
     * 
     * @type {Date}
     * @memberof Snapshot
     */
    createdAt: Date;
}

/**
 * Check if a given object implements the Snapshot interface.
 */
export function instanceOfSnapshot(value: object): value is Snapshot {
    if (!('inventory' in value) || value['inventory'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function SnapshotFromJSON(json: any): Snapshot {
    return SnapshotFromJSONTyped(json, false);
}

export function SnapshotFromJSONTyped(json: any, ignoreDiscriminator: boolean): Snapshot {
    if (json == null) {
        return json;
    }
    return {
        
        'inventory': InventoryFromJSON(json['inventory']),
        'createdAt': (new Date(json['createdAt'])),
    };
}

export function SnapshotToJSON(json: any): Snapshot {
    return SnapshotToJSONTyped(json, false);
}

export function SnapshotToJSONTyped(value?: Snapshot | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'inventory': InventoryToJSON(value['inventory']),
        'createdAt': value['createdAt'].toISOString(),
    };
}

