/* tslint:disable */
/* eslint-disable */
/**
 * Migration Planner API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: undefined
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { VmNetwork } from './VmNetwork.js';
import {
    VmNetworkFromJSON,
    VmNetworkFromJSONTyped,
    VmNetworkToJSON,
    VmNetworkToJSONTyped,
} from './VmNetwork.js';
import type { AgentProxy } from './AgentProxy.js';
import {
    AgentProxyFromJSON,
    AgentProxyFromJSONTyped,
    AgentProxyToJSON,
    AgentProxyToJSONTyped,
} from './AgentProxy.js';
import type { Label } from './Label.js';
import {
    LabelFromJSON,
    LabelFromJSONTyped,
    LabelToJSON,
    LabelToJSONTyped,
} from './Label.js';

/**
 * 
 * @export
 * @interface SourceUpdate
 */
export interface SourceUpdate {
    /**
     * 
     * @type {string}
     * @memberof SourceUpdate
     */
    name?: string;
    /**
     * 
     * @type {Array<Label>}
     * @memberof SourceUpdate
     */
    labels?: Array<Label>;
    /**
     * 
     * @type {string}
     * @memberof SourceUpdate
     */
    sshPublicKey?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SourceUpdate
     */
    certificateChain?: string | null;
    /**
     * 
     * @type {AgentProxy}
     * @memberof SourceUpdate
     */
    proxy?: AgentProxy;
    /**
     * 
     * @type {VmNetwork}
     * @memberof SourceUpdate
     */
    network?: VmNetwork;
}

/**
 * Check if a given object implements the SourceUpdate interface.
 */
export function instanceOfSourceUpdate(value: object): value is SourceUpdate {
    return true;
}

export function SourceUpdateFromJSON(json: any): SourceUpdate {
    return SourceUpdateFromJSONTyped(json, false);
}

export function SourceUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): SourceUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'labels': json['labels'] == null ? undefined : ((json['labels'] as Array<any>).map(LabelFromJSON)),
        'sshPublicKey': json['sshPublicKey'] == null ? undefined : json['sshPublicKey'],
        'certificateChain': json['certificateChain'] == null ? undefined : json['certificateChain'],
        'proxy': json['proxy'] == null ? undefined : AgentProxyFromJSON(json['proxy']),
        'network': json['network'] == null ? undefined : VmNetworkFromJSON(json['network']),
    };
}

export function SourceUpdateToJSON(json: any): SourceUpdate {
    return SourceUpdateToJSONTyped(json, false);
}

export function SourceUpdateToJSONTyped(value?: SourceUpdate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'labels': value['labels'] == null ? undefined : ((value['labels'] as Array<any>).map(LabelToJSON)),
        'sshPublicKey': value['sshPublicKey'],
        'certificateChain': value['certificateChain'],
        'proxy': AgentProxyToJSON(value['proxy']),
        'network': VmNetworkToJSON(value['network']),
    };
}

