/* tslint:disable */
/* eslint-disable */
/**
 * Migration Planner API
 * Based on: https://github.com/kubev2v/migration-planner/blob/e8c0ddb122bf87bd9fc79cba6e52d159a334f093/api/v1alpha1/openapi.yaml
 *
 * The version of the OpenAPI document: 0.4.0-e8c0ddb1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { VmNetwork } from './VmNetwork.js';
import {
    VmNetworkFromJSON,
    VmNetworkFromJSONTyped,
    VmNetworkToJSON,
    VmNetworkToJSONTyped,
} from './VmNetwork.js';
import type { AgentProxy } from './AgentProxy.js';
import {
    AgentProxyFromJSON,
    AgentProxyFromJSONTyped,
    AgentProxyToJSON,
    AgentProxyToJSONTyped,
} from './AgentProxy.js';

/**
 * 
 * @export
 * @interface SourceInfra
 */
export interface SourceInfra {
    /**
     * 
     * @type {AgentProxy}
     * @memberof SourceInfra
     */
    proxy?: AgentProxy;
    /**
     * 
     * @type {string}
     * @memberof SourceInfra
     */
    sshPublicKey?: string | null;
    /**
     * 
     * @type {VmNetwork}
     * @memberof SourceInfra
     */
    vmNetwork?: VmNetwork;
}

/**
 * Check if a given object implements the SourceInfra interface.
 */
export function instanceOfSourceInfra(value: object): value is SourceInfra {
    return true;
}

export function SourceInfraFromJSON(json: any): SourceInfra {
    return SourceInfraFromJSONTyped(json, false);
}

export function SourceInfraFromJSONTyped(json: any, ignoreDiscriminator: boolean): SourceInfra {
    if (json == null) {
        return json;
    }
    return {
        
        'proxy': json['proxy'] == null ? undefined : AgentProxyFromJSON(json['proxy']),
        'sshPublicKey': json['sshPublicKey'] == null ? undefined : json['sshPublicKey'],
        'vmNetwork': json['vmNetwork'] == null ? undefined : VmNetworkFromJSON(json['vmNetwork']),
    };
}

export function SourceInfraToJSON(json: any): SourceInfra {
    return SourceInfraToJSONTyped(json, false);
}

export function SourceInfraToJSONTyped(value?: SourceInfra | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'proxy': AgentProxyToJSON(value['proxy']),
        'sshPublicKey': value['sshPublicKey'],
        'vmNetwork': VmNetworkToJSON(value['vmNetwork']),
    };
}

