/* tslint:disable */
/* eslint-disable */
/**
 * Migration Planner API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: undefined
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Inventory } from './Inventory';
import {
    InventoryFromJSON,
    InventoryFromJSONTyped,
    InventoryToJSON,
} from './Inventory';

/**
 * 
 * @export
 * @interface UpdateInventory
 */
export interface UpdateInventory {
    /**
     * 
     * @type {string}
     * @memberof UpdateInventory
     */
    agentId: string;
    /**
     * 
     * @type {Inventory}
     * @memberof UpdateInventory
     */
    inventory: Inventory;
}

/**
 * Check if a given object implements the UpdateInventory interface.
 */
export function instanceOfUpdateInventory(value: object): value is UpdateInventory {
    if (!('agentId' in value) || value['agentId'] === undefined) return false;
    if (!('inventory' in value) || value['inventory'] === undefined) return false;
    return true;
}

export function UpdateInventoryFromJSON(json: any): UpdateInventory {
    return UpdateInventoryFromJSONTyped(json, false);
}

export function UpdateInventoryFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateInventory {
    if (json == null) {
        return json;
    }
    return {
        
        'agentId': json['agentId'],
        'inventory': InventoryFromJSON(json['inventory']),
    };
}

export function UpdateInventoryToJSON(value?: UpdateInventory | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'agentId': value['agentId'],
        'inventory': InventoryToJSON(value['inventory']),
    };
}

