/* tslint:disable */
/* eslint-disable */
/**
 * Migration Planner API
 * Based on: https://github.com/kubev2v/migration-planner/blob/e8c0ddb122bf87bd9fc79cba6e52d159a334f093/api/v1alpha1/openapi.yaml
 *
 * The version of the OpenAPI document: 0.4.0-e8c0ddb1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { Inventory } from './Inventory.js';
import {
    InventoryFromJSON,
    InventoryFromJSONTyped,
    InventoryToJSON,
    InventoryToJSONTyped,
} from './Inventory.js';

/**
 * 
 * @export
 * @interface UpdateInventory
 */
export interface UpdateInventory {
    /**
     * 
     * @type {string}
     * @memberof UpdateInventory
     */
    agentId: string;
    /**
     * 
     * @type {Inventory}
     * @memberof UpdateInventory
     */
    inventory: Inventory;
}

/**
 * Check if a given object implements the UpdateInventory interface.
 */
export function instanceOfUpdateInventory(value: object): value is UpdateInventory {
    if (!('agentId' in value) || value['agentId'] === undefined) return false;
    if (!('inventory' in value) || value['inventory'] === undefined) return false;
    return true;
}

export function UpdateInventoryFromJSON(json: any): UpdateInventory {
    return UpdateInventoryFromJSONTyped(json, false);
}

export function UpdateInventoryFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateInventory {
    if (json == null) {
        return json;
    }
    return {
        
        'agentId': json['agentId'],
        'inventory': InventoryFromJSON(json['inventory']),
    };
}

export function UpdateInventoryToJSON(json: any): UpdateInventory {
    return UpdateInventoryToJSONTyped(json, false);
}

export function UpdateInventoryToJSONTyped(value?: UpdateInventory | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'agentId': value['agentId'],
        'inventory': InventoryToJSON(value['inventory']),
    };
}

