/* tslint:disable */
/* eslint-disable */
/**
 * Migration Planner API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: undefined
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VCenter
 */
export interface VCenter {
    /**
     * 
     * @type {string}
     * @memberof VCenter
     */
    id: string;
}

/**
 * Check if a given object implements the VCenter interface.
 */
export function instanceOfVCenter(value: object): value is VCenter {
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function VCenterFromJSON(json: any): VCenter {
    return VCenterFromJSONTyped(json, false);
}

export function VCenterFromJSONTyped(json: any, ignoreDiscriminator: boolean): VCenter {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
    };
}

export function VCenterToJSON(value?: VCenter | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
    };
}

