/* tslint:disable */
/* eslint-disable */
/**
 * Migration Planner API
 * Based on: https://github.com/kubev2v/migration-planner/blob/bd435bf4e63611a5d609f7c918e85dd57830fccf/api/v1alpha1/openapi.yaml
 *
 * The version of the OpenAPI document: 0.4.0-bd435bf4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { Ipv4Config } from './Ipv4Config.js';
import {
    Ipv4ConfigFromJSON,
    Ipv4ConfigFromJSONTyped,
    Ipv4ConfigToJSON,
    Ipv4ConfigToJSONTyped,
} from './Ipv4Config.js';

/**
 * 
 * @export
 * @interface VmNetwork
 */
export interface VmNetwork {
    /**
     * 
     * @type {Ipv4Config}
     * @memberof VmNetwork
     */
    ipv4?: Ipv4Config;
}

/**
 * Check if a given object implements the VmNetwork interface.
 */
export function instanceOfVmNetwork(value: object): value is VmNetwork {
    return true;
}

export function VmNetworkFromJSON(json: any): VmNetwork {
    return VmNetworkFromJSONTyped(json, false);
}

export function VmNetworkFromJSONTyped(json: any, ignoreDiscriminator: boolean): VmNetwork {
    if (json == null) {
        return json;
    }
    return {
        
        'ipv4': json['ipv4'] == null ? undefined : Ipv4ConfigFromJSON(json['ipv4']),
    };
}

export function VmNetworkToJSON(json: any): VmNetwork {
    return VmNetworkToJSONTyped(json, false);
}

export function VmNetworkToJSONTyped(value?: VmNetwork | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ipv4': Ipv4ConfigToJSON(value['ipv4']),
    };
}

