/* tslint:disable */
/* eslint-disable */
/**
 * Migration Planner API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: undefined
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Ipv4Config } from './Ipv4Config';
import {
    Ipv4ConfigFromJSON,
    Ipv4ConfigFromJSONTyped,
    Ipv4ConfigToJSON,
} from './Ipv4Config';

/**
 * 
 * @export
 * @interface VmNetwork
 */
export interface VmNetwork {
    /**
     * 
     * @type {Ipv4Config}
     * @memberof VmNetwork
     */
    ipv4?: Ipv4Config;
}

/**
 * Check if a given object implements the VmNetwork interface.
 */
export function instanceOfVmNetwork(value: object): value is VmNetwork {
    return true;
}

export function VmNetworkFromJSON(json: any): VmNetwork {
    return VmNetworkFromJSONTyped(json, false);
}

export function VmNetworkFromJSONTyped(json: any, ignoreDiscriminator: boolean): VmNetwork {
    if (json == null) {
        return json;
    }
    return {
        
        'ipv4': json['ipv4'] == null ? undefined : Ipv4ConfigFromJSON(json['ipv4']),
    };
}

export function VmNetworkToJSON(value?: VmNetwork | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'ipv4': Ipv4ConfigToJSON(value['ipv4']),
    };
}

