/* tslint:disable */
/* eslint-disable */
/**
 * Migration Planner API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: undefined
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VMResourceBreakdownHistogram
 */
export interface VMResourceBreakdownHistogram {
    /**
     * 
     * @type {number}
     * @memberof VMResourceBreakdownHistogram
     */
    minValue: number;
    /**
     * 
     * @type {number}
     * @memberof VMResourceBreakdownHistogram
     */
    step: number;
    /**
     * 
     * @type {Array<number>}
     * @memberof VMResourceBreakdownHistogram
     */
    data: Array<number>;
}

/**
 * Check if a given object implements the VMResourceBreakdownHistogram interface.
 */
export function instanceOfVMResourceBreakdownHistogram(value: object): value is VMResourceBreakdownHistogram {
    if (!('minValue' in value) || value['minValue'] === undefined) return false;
    if (!('step' in value) || value['step'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function VMResourceBreakdownHistogramFromJSON(json: any): VMResourceBreakdownHistogram {
    return VMResourceBreakdownHistogramFromJSONTyped(json, false);
}

export function VMResourceBreakdownHistogramFromJSONTyped(json: any, ignoreDiscriminator: boolean): VMResourceBreakdownHistogram {
    if (json == null) {
        return json;
    }
    return {
        
        'minValue': json['minValue'],
        'step': json['step'],
        'data': json['data'],
    };
}

export function VMResourceBreakdownHistogramToJSON(value?: VMResourceBreakdownHistogram | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'minValue': value['minValue'],
        'step': value['step'],
        'data': value['data'],
    };
}

