/* tslint:disable */
/* eslint-disable */
/**
 * Migration Planner API - agent endpoint
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: undefined
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface AgentStatusUpdate
 */
export interface AgentStatusUpdate {
    /**
     * 
     * @type {string}
     * @memberof AgentStatusUpdate
     */
    status: string;
    /**
     * 
     * @type {string}
     * @memberof AgentStatusUpdate
     */
    statusInfo: string;
    /**
     * 
     * @type {string}
     * @memberof AgentStatusUpdate
     */
    credentialUrl: string;
    /**
     * 
     * @type {string}
     * @memberof AgentStatusUpdate
     */
    version: string;
    /**
     * 
     * @type {string}
     * @memberof AgentStatusUpdate
     */
    sourceId: string;
}

/**
 * Check if a given object implements the AgentStatusUpdate interface.
 */
export function instanceOfAgentStatusUpdate(value: object): value is AgentStatusUpdate {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('statusInfo' in value) || value['statusInfo'] === undefined) return false;
    if (!('credentialUrl' in value) || value['credentialUrl'] === undefined) return false;
    if (!('version' in value) || value['version'] === undefined) return false;
    if (!('sourceId' in value) || value['sourceId'] === undefined) return false;
    return true;
}

export function AgentStatusUpdateFromJSON(json: any): AgentStatusUpdate {
    return AgentStatusUpdateFromJSONTyped(json, false);
}

export function AgentStatusUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): AgentStatusUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
        'statusInfo': json['statusInfo'],
        'credentialUrl': json['credentialUrl'],
        'version': json['version'],
        'sourceId': json['sourceId'],
    };
}

export function AgentStatusUpdateToJSON(json: any): AgentStatusUpdate {
    return AgentStatusUpdateToJSONTyped(json, false);
}

export function AgentStatusUpdateToJSONTyped(value?: AgentStatusUpdate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'statusInfo': value['statusInfo'],
        'credentialUrl': value['credentialUrl'],
        'version': value['version'],
        'sourceId': value['sourceId'],
    };
}

