/* tslint:disable */
/* eslint-disable */
/**
 * Assisted Migration Agent API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface AgentStatus
 */
export interface AgentStatus {
    /**
     * Target mode for the agent
     * @type {string}
     * @memberof AgentStatus
     */
    mode: AgentStatusModeEnum;
    /**
     * Current console connection status
     * @type {string}
     * @memberof AgentStatus
     */
    consoleConnection: AgentStatusConsoleConnectionEnum;
    /**
     * Connection error description
     * @type {string}
     * @memberof AgentStatus
     */
    error?: string;
}


/**
 * @export
 */
export const AgentStatusModeEnum = {
    Connected: 'connected',
    Disconnected: 'disconnected'
} as const;
export type AgentStatusModeEnum = typeof AgentStatusModeEnum[keyof typeof AgentStatusModeEnum];

/**
 * @export
 */
export const AgentStatusConsoleConnectionEnum = {
    Disconnected: 'disconnected',
    Connected: 'connected'
} as const;
export type AgentStatusConsoleConnectionEnum = typeof AgentStatusConsoleConnectionEnum[keyof typeof AgentStatusConsoleConnectionEnum];


/**
 * Check if a given object implements the AgentStatus interface.
 */
export function instanceOfAgentStatus(value: object): value is AgentStatus {
    if (!('mode' in value) || value['mode'] === undefined) return false;
    if (!('consoleConnection' in value) || value['consoleConnection'] === undefined) return false;
    return true;
}

export function AgentStatusFromJSON(json: any): AgentStatus {
    return AgentStatusFromJSONTyped(json, false);
}

export function AgentStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): AgentStatus {
    if (json == null) {
        return json;
    }
    return {
        
        'mode': json['mode'],
        'consoleConnection': json['console_connection'],
        'error': json['error'] == null ? undefined : json['error'],
    };
}

export function AgentStatusToJSON(json: any): AgentStatus {
    return AgentStatusToJSONTyped(json, false);
}

export function AgentStatusToJSONTyped(value?: AgentStatus | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'mode': value['mode'],
        'console_connection': value['consoleConnection'],
        'error': value['error'],
    };
}

