/* tslint:disable */
/* eslint-disable */
/**
 * Assisted Migration Agent API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface CollectorStatus
 */
export interface CollectorStatus {
    /**
     * 
     * @type {string}
     * @memberof CollectorStatus
     */
    status: CollectorStatusStatusEnum;
    /**
     * Error message when status is error
     * @type {string}
     * @memberof CollectorStatus
     */
    error?: string;
}


/**
 * @export
 */
export const CollectorStatusStatusEnum = {
    Ready: 'ready',
    Connecting: 'connecting',
    Connected: 'connected',
    Collecting: 'collecting',
    Parsing: 'parsing',
    Collected: 'collected',
    Error: 'error'
} as const;
export type CollectorStatusStatusEnum = typeof CollectorStatusStatusEnum[keyof typeof CollectorStatusStatusEnum];


/**
 * Check if a given object implements the CollectorStatus interface.
 */
export function instanceOfCollectorStatus(value: object): value is CollectorStatus {
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function CollectorStatusFromJSON(json: any): CollectorStatus {
    return CollectorStatusFromJSONTyped(json, false);
}

export function CollectorStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): CollectorStatus {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
        'error': json['error'] == null ? undefined : json['error'],
    };
}

export function CollectorStatusToJSON(json: any): CollectorStatus {
    return CollectorStatusToJSONTyped(json, false);
}

export function CollectorStatusToJSONTyped(value?: CollectorStatus | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'error': value['error'],
    };
}

