/* tslint:disable */
/* eslint-disable */
/**
 * Assisted Migration Agent API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface CreateGroupRequest
 */
export interface CreateGroupRequest {
    /**
     * Group display name
     * @type {string}
     * @memberof CreateGroupRequest
     */
    name: string;
    /**
     * Optional group description
     * @type {string}
     * @memberof CreateGroupRequest
     */
    description?: string;
    /**
     * Filter expression (will be validated)
     * @type {string}
     * @memberof CreateGroupRequest
     */
    filter: string;
}

/**
 * Check if a given object implements the CreateGroupRequest interface.
 */
export function instanceOfCreateGroupRequest(value: object): value is CreateGroupRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('filter' in value) || value['filter'] === undefined) return false;
    return true;
}

export function CreateGroupRequestFromJSON(json: any): CreateGroupRequest {
    return CreateGroupRequestFromJSONTyped(json, false);
}

export function CreateGroupRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateGroupRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'filter': json['filter'],
    };
}

export function CreateGroupRequestToJSON(json: any): CreateGroupRequest {
    return CreateGroupRequestToJSONTyped(json, false);
}

export function CreateGroupRequestToJSONTyped(value?: CreateGroupRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
        'filter': value['filter'],
    };
}

