/* tslint:disable */
/* eslint-disable */
/**
 * Migration Planner Agent UI API
 * API endpoints for the agent UI to interact with the migration discovery VM
 *
 * The version of the OpenAPI document: undefined
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * VMware credentials for the discovery process
 * @export
 * @interface Credentials
 */
export interface Credentials {
    /**
     * URL of the VMware vCenter server
     * @type {string}
     * @memberof Credentials
     */
    url: string;
    /**
     * Username for VMware authentication
     * @type {string}
     * @memberof Credentials
     */
    username: string;
    /**
     * Password for VMware authentication
     * @type {string}
     * @memberof Credentials
     */
    password: string;
    /**
     * Whether the user agrees to share aggregated data with Red Hat
     * @type {boolean}
     * @memberof Credentials
     */
    isDataSharingAllowed?: boolean;
}

/**
 * Check if a given object implements the Credentials interface.
 */
export function instanceOfCredentials(value: object): value is Credentials {
    if (!('url' in value) || value['url'] === undefined) return false;
    if (!('username' in value) || value['username'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    return true;
}

export function CredentialsFromJSON(json: any): Credentials {
    return CredentialsFromJSONTyped(json, false);
}

export function CredentialsFromJSONTyped(json: any, ignoreDiscriminator: boolean): Credentials {
    if (json == null) {
        return json;
    }
    return {
        
        'url': json['url'],
        'username': json['username'],
        'password': json['password'],
        'isDataSharingAllowed': json['isDataSharingAllowed'] == null ? undefined : json['isDataSharingAllowed'],
    };
}

export function CredentialsToJSON(json: any): Credentials {
    return CredentialsToJSONTyped(json, false);
}

export function CredentialsToJSONTyped(value?: Credentials | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'url': value['url'],
        'username': value['username'],
        'password': value['password'],
        'isDataSharingAllowed': value['isDataSharingAllowed'],
    };
}

