/* tslint:disable */
/* eslint-disable */
/**
 * Migration Planner API - agent endpoint
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: undefined
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface Datastore
 */
export interface Datastore {
    /**
     * 
     * @type {string}
     * @memberof Datastore
     */
    type: string;
    /**
     * 
     * @type {number}
     * @memberof Datastore
     */
    totalCapacityGB: number;
    /**
     * 
     * @type {number}
     * @memberof Datastore
     */
    freeCapacityGB: number;
    /**
     * 
     * @type {string}
     * @memberof Datastore
     */
    vendor: string;
    /**
     * 
     * @type {string}
     * @memberof Datastore
     */
    diskId: string;
    /**
     * 
     * @type {boolean}
     * @memberof Datastore
     */
    hardwareAcceleratedMove: boolean;
    /**
     * 
     * @type {string}
     * @memberof Datastore
     */
    protocolType: string;
    /**
     * 
     * @type {string}
     * @memberof Datastore
     */
    model: string;
    /**
     * Identifier of the host where this datastore is attached
     * @type {string}
     * @memberof Datastore
     */
    hostId?: string | null;
}

/**
 * Check if a given object implements the Datastore interface.
 */
export function instanceOfDatastore(value: object): value is Datastore {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('totalCapacityGB' in value) || value['totalCapacityGB'] === undefined) return false;
    if (!('freeCapacityGB' in value) || value['freeCapacityGB'] === undefined) return false;
    if (!('vendor' in value) || value['vendor'] === undefined) return false;
    if (!('diskId' in value) || value['diskId'] === undefined) return false;
    if (!('hardwareAcceleratedMove' in value) || value['hardwareAcceleratedMove'] === undefined) return false;
    if (!('protocolType' in value) || value['protocolType'] === undefined) return false;
    if (!('model' in value) || value['model'] === undefined) return false;
    return true;
}

export function DatastoreFromJSON(json: any): Datastore {
    return DatastoreFromJSONTyped(json, false);
}

export function DatastoreFromJSONTyped(json: any, ignoreDiscriminator: boolean): Datastore {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'totalCapacityGB': json['totalCapacityGB'],
        'freeCapacityGB': json['freeCapacityGB'],
        'vendor': json['vendor'],
        'diskId': json['diskId'],
        'hardwareAcceleratedMove': json['hardwareAcceleratedMove'],
        'protocolType': json['protocolType'],
        'model': json['model'],
        'hostId': json['hostId'] == null ? undefined : json['hostId'],
    };
}

export function DatastoreToJSON(json: any): Datastore {
    return DatastoreToJSONTyped(json, false);
}

export function DatastoreToJSONTyped(value?: Datastore | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'totalCapacityGB': value['totalCapacityGB'],
        'freeCapacityGB': value['freeCapacityGB'],
        'vendor': value['vendor'],
        'diskId': value['diskId'],
        'hardwareAcceleratedMove': value['hardwareAcceleratedMove'],
        'protocolType': value['protocolType'],
        'model': value['model'],
        'hostId': value['hostId'],
    };
}

