/* tslint:disable */
/* eslint-disable */
/**
 * Assisted Migration Agent API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Inventory } from './Inventory.js';
import {
    instanceOfInventory,
    InventoryFromJSON,
    InventoryFromJSONTyped,
    InventoryToJSON,
} from './Inventory.js';
import type { UpdateInventory } from './UpdateInventory.js';
import {
    instanceOfUpdateInventory,
    UpdateInventoryFromJSON,
    UpdateInventoryFromJSONTyped,
    UpdateInventoryToJSON,
} from './UpdateInventory.js';

/**
 * @type GetInventory200Response
 * 
 * @export
 */
export type GetInventory200Response = Inventory | UpdateInventory;

export function GetInventory200ResponseFromJSON(json: any): GetInventory200Response {
    return GetInventory200ResponseFromJSONTyped(json, false);
}

export function GetInventory200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetInventory200Response {
    if (json == null) {
        return json;
    }
    if (typeof json !== 'object') {
        return json;
    }
    // Check for UpdateInventory format (has both agentId and inventory fields)
    if ('agentId' in json && 'inventory' in json) {
        return UpdateInventoryFromJSONTyped(json, true);
    }
    // Check for Inventory format (has vcenter_id in snake_case from server)
    if ('vcenter_id' in json && 'clusters' in json) {
        return InventoryFromJSONTyped(json, true);
    }
    // Fallback: try to parse as Inventory
    if ('vcenterId' in json && 'clusters' in json) {
        return InventoryFromJSONTyped(json, true);
    }
    return {} as any;
}

export function GetInventory200ResponseToJSON(json: any): any {
    return GetInventory200ResponseToJSONTyped(json, false);
}

export function GetInventory200ResponseToJSONTyped(value?: GetInventory200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value !== 'object') {
        return value;
    }
    if (instanceOfInventory(value)) {
        return InventoryToJSON(value as Inventory);
    }
    if (instanceOfUpdateInventory(value)) {
        return UpdateInventoryToJSON(value as UpdateInventory);
    }
    return {};
}

