/* tslint:disable */
/* eslint-disable */
/**
 * Assisted Migration Agent API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { Group } from './Group.js';
import {
    GroupFromJSON,
    GroupFromJSONTyped,
    GroupToJSON,
    GroupToJSONTyped,
} from './Group.js';
import type { VirtualMachine } from './VirtualMachine.js';
import {
    VirtualMachineFromJSON,
    VirtualMachineFromJSONTyped,
    VirtualMachineToJSON,
    VirtualMachineToJSONTyped,
} from './VirtualMachine.js';

/**
 * 
 * @export
 * @interface GroupResponse
 */
export interface GroupResponse {
    /**
     * 
     * @type {Group}
     * @memberof GroupResponse
     */
    group: Group;
    /**
     * 
     * @type {Array<VirtualMachine>}
     * @memberof GroupResponse
     */
    vms: Array<VirtualMachine>;
    /**
     * Total number of VMs matching the group's filter
     * @type {number}
     * @memberof GroupResponse
     */
    total: number;
    /**
     * Current page number
     * @type {number}
     * @memberof GroupResponse
     */
    page: number;
    /**
     * Total number of pages
     * @type {number}
     * @memberof GroupResponse
     */
    pageCount: number;
}

/**
 * Check if a given object implements the GroupResponse interface.
 */
export function instanceOfGroupResponse(value: object): value is GroupResponse {
    if (!('group' in value) || value['group'] === undefined) return false;
    if (!('vms' in value) || value['vms'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('page' in value) || value['page'] === undefined) return false;
    if (!('pageCount' in value) || value['pageCount'] === undefined) return false;
    return true;
}

export function GroupResponseFromJSON(json: any): GroupResponse {
    return GroupResponseFromJSONTyped(json, false);
}

export function GroupResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GroupResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'group': GroupFromJSON(json['group']),
        'vms': ((json['vms'] as Array<any>).map(VirtualMachineFromJSON)),
        'total': json['total'],
        'page': json['page'],
        'pageCount': json['pageCount'],
    };
}

export function GroupResponseToJSON(json: any): GroupResponse {
    return GroupResponseToJSONTyped(json, false);
}

export function GroupResponseToJSONTyped(value?: GroupResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'group': GroupToJSON(value['group']),
        'vms': ((value['vms'] as Array<any>).map(VirtualMachineToJSON)),
        'total': value['total'],
        'page': value['page'],
        'pageCount': value['pageCount'],
    };
}

