/* tslint:disable */
/* eslint-disable */
/**
 * Assisted Migration Agent API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { Group } from './Group.js';
import {
    GroupFromJSON,
    GroupFromJSONTyped,
    GroupToJSON,
    GroupToJSONTyped,
} from './Group.js';

/**
 * 
 * @export
 * @interface GroupListResponse
 */
export interface GroupListResponse {
    /**
     * 
     * @type {Array<Group>}
     * @memberof GroupListResponse
     */
    groups: Array<Group>;
    /**
     * Total number of groups
     * @type {number}
     * @memberof GroupListResponse
     */
    total: number;
    /**
     * Current page number
     * @type {number}
     * @memberof GroupListResponse
     */
    page: number;
    /**
     * Total number of pages
     * @type {number}
     * @memberof GroupListResponse
     */
    pageCount: number;
}

/**
 * Check if a given object implements the GroupListResponse interface.
 */
export function instanceOfGroupListResponse(value: object): value is GroupListResponse {
    if (!('groups' in value) || value['groups'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('page' in value) || value['page'] === undefined) return false;
    if (!('pageCount' in value) || value['pageCount'] === undefined) return false;
    return true;
}

export function GroupListResponseFromJSON(json: any): GroupListResponse {
    return GroupListResponseFromJSONTyped(json, false);
}

export function GroupListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GroupListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'groups': ((json['groups'] as Array<any>).map(GroupFromJSON)),
        'total': json['total'],
        'page': json['page'],
        'pageCount': json['pageCount'],
    };
}

export function GroupListResponseToJSON(json: any): GroupListResponse {
    return GroupListResponseToJSONTyped(json, false);
}

export function GroupListResponseToJSONTyped(value?: GroupListResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'groups': ((value['groups'] as Array<any>).map(GroupToJSON)),
        'total': value['total'],
        'page': value['page'],
        'pageCount': value['pageCount'],
    };
}

