/* tslint:disable */
/* eslint-disable */
/**
 * Assisted Migration Agent API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface GuestNetwork
 */
export interface GuestNetwork {
    /**
     * Name of the network device inside the guest OS
     * @type {string}
     * @memberof GuestNetwork
     */
    device?: string;
    /**
     * MAC address as seen by the guest OS
     * @type {string}
     * @memberof GuestNetwork
     */
    mac?: string;
    /**
     * IP address assigned to this interface
     * @type {string}
     * @memberof GuestNetwork
     */
    ip?: string;
    /**
     * Network prefix length (subnet mask in CIDR notation)
     * @type {number}
     * @memberof GuestNetwork
     */
    prefixLength?: number;
    /**
     * Network name as reported by the guest OS
     * @type {string}
     * @memberof GuestNetwork
     */
    network?: string;
}

/**
 * Check if a given object implements the GuestNetwork interface.
 */
export function instanceOfGuestNetwork(value: object): value is GuestNetwork {
    return true;
}

export function GuestNetworkFromJSON(json: any): GuestNetwork {
    return GuestNetworkFromJSONTyped(json, false);
}

export function GuestNetworkFromJSONTyped(json: any, ignoreDiscriminator: boolean): GuestNetwork {
    if (json == null) {
        return json;
    }
    return {
        
        'device': json['device'] == null ? undefined : json['device'],
        'mac': json['mac'] == null ? undefined : json['mac'],
        'ip': json['ip'] == null ? undefined : json['ip'],
        'prefixLength': json['prefixLength'] == null ? undefined : json['prefixLength'],
        'network': json['network'] == null ? undefined : json['network'],
    };
}

export function GuestNetworkToJSON(json: any): GuestNetwork {
    return GuestNetworkToJSONTyped(json, false);
}

export function GuestNetworkToJSONTyped(value?: GuestNetwork | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'device': value['device'],
        'mac': value['mac'],
        'ip': value['ip'],
        'prefixLength': value['prefixLength'],
        'network': value['network'],
    };
}

