/* tslint:disable */
/* eslint-disable */
/**
 * Migration Planner Agent UI API
 * API endpoints for the agent UI to interact with the migration discovery VM
 *
 * The version of the OpenAPI document: undefined
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface Host
 */
export interface Host {
    /**
     * Unique identifier for this host
     * @type {string}
     * @memberof Host
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof Host
     */
    vendor: string;
    /**
     * 
     * @type {string}
     * @memberof Host
     */
    model: string;
    /**
     * Number of CPU cores
     * @type {number}
     * @memberof Host
     */
    cpuCores?: number | null;
    /**
     * Number of CPU sockets
     * @type {number}
     * @memberof Host
     */
    cpuSockets?: number | null;
    /**
     * Host memory in MB
     * @type {number}
     * @memberof Host
     */
    memoryMB?: number | null;
}

/**
 * Check if a given object implements the Host interface.
 */
export function instanceOfHost(value: object): value is Host {
    if (!('vendor' in value) || value['vendor'] === undefined) return false;
    if (!('model' in value) || value['model'] === undefined) return false;
    return true;
}

export function HostFromJSON(json: any): Host {
    return HostFromJSONTyped(json, false);
}

export function HostFromJSONTyped(json: any, ignoreDiscriminator: boolean): Host {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'vendor': json['vendor'],
        'model': json['model'],
        'cpuCores': json['cpuCores'] == null ? undefined : json['cpuCores'],
        'cpuSockets': json['cpuSockets'] == null ? undefined : json['cpuSockets'],
        'memoryMB': json['memoryMB'] == null ? undefined : json['memoryMB'],
    };
}

export function HostToJSON(json: any): Host {
    return HostToJSONTyped(json, false);
}

export function HostToJSONTyped(value?: Host | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'vendor': value['vendor'],
        'model': value['model'],
        'cpuCores': value['cpuCores'],
        'cpuSockets': value['cpuSockets'],
        'memoryMB': value['memoryMB'],
    };
}

