/* tslint:disable */
/* eslint-disable */
/**
 * Migration Planner API - agent endpoint
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: undefined
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InfraNetworksInner
 */
export interface InfraNetworksInner {
    /**
     * 
     * @type {string}
     * @memberof InfraNetworksInner
     */
    type: InfraNetworksInnerTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof InfraNetworksInner
     */
    name: string;
}


/**
 * @export
 */
export const InfraNetworksInnerTypeEnum = {
    Standard: 'standard',
    Distributed: 'distributed'
} as const;
export type InfraNetworksInnerTypeEnum = typeof InfraNetworksInnerTypeEnum[keyof typeof InfraNetworksInnerTypeEnum];


/**
 * Check if a given object implements the InfraNetworksInner interface.
 */
export function instanceOfInfraNetworksInner(value: object): value is InfraNetworksInner {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function InfraNetworksInnerFromJSON(json: any): InfraNetworksInner {
    return InfraNetworksInnerFromJSONTyped(json, false);
}

export function InfraNetworksInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): InfraNetworksInner {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'name': json['name'],
    };
}

export function InfraNetworksInnerToJSON(value?: InfraNetworksInner | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'type': value['type'],
        'name': value['name'],
    };
}

