/* tslint:disable */
/* eslint-disable */
/**
 * Assisted Migration Agent API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface InspectorStatus
 */
export interface InspectorStatus {
    /**
     * Inspector state
     * @type {string}
     * @memberof InspectorStatus
     */
    state: InspectorStatusStateEnum;
    /**
     * Error message when state is error
     * @type {string}
     * @memberof InspectorStatus
     */
    error?: string;
}


/**
 * @export
 */
export const InspectorStatusStateEnum = {
    Ready: 'ready',
    Initiating: 'Initiating',
    Running: 'running',
    Canceling: 'canceling',
    Canceled: 'canceled',
    Completed: 'completed',
    Error: 'error'
} as const;
export type InspectorStatusStateEnum = typeof InspectorStatusStateEnum[keyof typeof InspectorStatusStateEnum];


/**
 * Check if a given object implements the InspectorStatus interface.
 */
export function instanceOfInspectorStatus(value: object): value is InspectorStatus {
    if (!('state' in value) || value['state'] === undefined) return false;
    return true;
}

export function InspectorStatusFromJSON(json: any): InspectorStatus {
    return InspectorStatusFromJSONTyped(json, false);
}

export function InspectorStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): InspectorStatus {
    if (json == null) {
        return json;
    }
    return {
        
        'state': json['state'],
        'error': json['error'] == null ? undefined : json['error'],
    };
}

export function InspectorStatusToJSON(json: any): InspectorStatus {
    return InspectorStatusToJSONTyped(json, false);
}

export function InspectorStatusToJSONTyped(value?: InspectorStatus | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'state': value['state'],
        'error': value['error'],
    };
}

