/* tslint:disable */
/* eslint-disable */
/**
 * Assisted Migration Agent API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { VcenterCredentials } from './VcenterCredentials.js';
import {
    VcenterCredentialsFromJSON,
    VcenterCredentialsFromJSONTyped,
    VcenterCredentialsToJSON,
    VcenterCredentialsToJSONTyped,
} from './VcenterCredentials.js';

/**
 * 
 * @export
 * @interface InspectorStartRequest
 */
export interface InspectorStartRequest {
    /**
     * 
     * @type {VcenterCredentials}
     * @memberof InspectorStartRequest
     */
    vcenterCredentials: VcenterCredentials;
    /**
     * Array of VM id
     * @type {Array<string>}
     * @memberof InspectorStartRequest
     */
    vmIds: Array<string>;
}

/**
 * Check if a given object implements the InspectorStartRequest interface.
 */
export function instanceOfInspectorStartRequest(value: object): value is InspectorStartRequest {
    if (!('vcenterCredentials' in value) || value['vcenterCredentials'] === undefined) return false;
    if (!('vmIds' in value) || value['vmIds'] === undefined) return false;
    return true;
}

export function InspectorStartRequestFromJSON(json: any): InspectorStartRequest {
    return InspectorStartRequestFromJSONTyped(json, false);
}

export function InspectorStartRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): InspectorStartRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'vcenterCredentials': VcenterCredentialsFromJSON(json['VcenterCredentials']),
        'vmIds': json['vmIds'],
    };
}

export function InspectorStartRequestToJSON(json: any): InspectorStartRequest {
    return InspectorStartRequestToJSONTyped(json, false);
}

export function InspectorStartRequestToJSONTyped(value?: InspectorStartRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'VcenterCredentials': VcenterCredentialsToJSON(value['vcenterCredentials']),
        'vmIds': value['vmIds'],
    };
}

