/* tslint:disable */
/* eslint-disable */
/**
 * Migration Planner API - agent endpoint
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: undefined
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MigrationIssuesInner
 */
export interface MigrationIssuesInner {
    /**
     * 
     * @type {string}
     * @memberof MigrationIssuesInner
     */
    label: string;
    /**
     * 
     * @type {string}
     * @memberof MigrationIssuesInner
     */
    assessment: string;
    /**
     * 
     * @type {number}
     * @memberof MigrationIssuesInner
     */
    count: number;
}

/**
 * Check if a given object implements the MigrationIssuesInner interface.
 */
export function instanceOfMigrationIssuesInner(value: object): value is MigrationIssuesInner {
    if (!('label' in value) || value['label'] === undefined) return false;
    if (!('assessment' in value) || value['assessment'] === undefined) return false;
    if (!('count' in value) || value['count'] === undefined) return false;
    return true;
}

export function MigrationIssuesInnerFromJSON(json: any): MigrationIssuesInner {
    return MigrationIssuesInnerFromJSONTyped(json, false);
}

export function MigrationIssuesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): MigrationIssuesInner {
    if (json == null) {
        return json;
    }
    return {
        
        'label': json['label'],
        'assessment': json['assessment'],
        'count': json['count'],
    };
}

export function MigrationIssuesInnerToJSON(value?: MigrationIssuesInner | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'label': value['label'],
        'assessment': value['assessment'],
        'count': value['count'],
    };
}

