/* tslint:disable */
/* eslint-disable */
/**
 * Migration Planner Agent UI API
 * API endpoints for the agent UI to interact with the migration discovery VM
 *
 * The version of the OpenAPI document: undefined
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface ServiceUIReply
 */
export interface ServiceUIReply {
    /**
     * URL of the planner service UI
     * @type {string}
     * @memberof ServiceUIReply
     */
    url: string;
}

/**
 * Check if a given object implements the ServiceUIReply interface.
 */
export function instanceOfServiceUIReply(value: object): value is ServiceUIReply {
    if (!('url' in value) || value['url'] === undefined) return false;
    return true;
}

export function ServiceUIReplyFromJSON(json: any): ServiceUIReply {
    return ServiceUIReplyFromJSONTyped(json, false);
}

export function ServiceUIReplyFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServiceUIReply {
    if (json == null) {
        return json;
    }
    return {
        
        'url': json['url'],
    };
}

export function ServiceUIReplyToJSON(json: any): ServiceUIReply {
    return ServiceUIReplyToJSONTyped(json, false);
}

export function ServiceUIReplyToJSONTyped(value?: ServiceUIReply | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'url': value['url'],
    };
}

