/* tslint:disable */
/* eslint-disable */
/**
 * Migration Planner API - agent endpoint
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: undefined
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Inventory } from './Inventory';
import {
    InventoryFromJSON,
    InventoryFromJSONTyped,
    InventoryToJSON,
} from './Inventory';

/**
 * 
 * @export
 * @interface SourceStatusUpdate
 */
export interface SourceStatusUpdate {
    /**
     * 
     * @type {string}
     * @memberof SourceStatusUpdate
     */
    status: string;
    /**
     * 
     * @type {string}
     * @memberof SourceStatusUpdate
     */
    statusInfo: string;
    /**
     * 
     * @type {Inventory}
     * @memberof SourceStatusUpdate
     */
    inventory?: Inventory;
    /**
     * 
     * @type {string}
     * @memberof SourceStatusUpdate
     */
    credentialUrl: string;
}

/**
 * Check if a given object implements the SourceStatusUpdate interface.
 */
export function instanceOfSourceStatusUpdate(value: object): value is SourceStatusUpdate {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('statusInfo' in value) || value['statusInfo'] === undefined) return false;
    if (!('credentialUrl' in value) || value['credentialUrl'] === undefined) return false;
    return true;
}

export function SourceStatusUpdateFromJSON(json: any): SourceStatusUpdate {
    return SourceStatusUpdateFromJSONTyped(json, false);
}

export function SourceStatusUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): SourceStatusUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
        'statusInfo': json['statusInfo'],
        'inventory': json['inventory'] == null ? undefined : InventoryFromJSON(json['inventory']),
        'credentialUrl': json['credentialUrl'],
    };
}

export function SourceStatusUpdateToJSON(value?: SourceStatusUpdate | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'status': value['status'],
        'statusInfo': value['statusInfo'],
        'inventory': InventoryToJSON(value['inventory']),
        'credentialUrl': value['credentialUrl'],
    };
}

