/* tslint:disable */
/* eslint-disable */
/**
 * Migration Planner API - agent endpoint
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: undefined
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { SourceInfra } from './SourceInfra.js';
import {
    SourceInfraFromJSON,
    SourceInfraFromJSONTyped,
    SourceInfraToJSON,
    SourceInfraToJSONTyped,
} from './SourceInfra.js';
import type { Agent } from './Agent.js';
import {
    AgentFromJSON,
    AgentFromJSONTyped,
    AgentToJSON,
    AgentToJSONTyped,
} from './Agent.js';
import type { Label } from './Label.js';
import {
    LabelFromJSON,
    LabelFromJSONTyped,
    LabelToJSON,
    LabelToJSONTyped,
} from './Label.js';
import type { Inventory } from './Inventory.js';
import {
    InventoryFromJSON,
    InventoryFromJSONTyped,
    InventoryToJSON,
    InventoryToJSONTyped,
} from './Inventory.js';

/**
 * 
 * @export
 * @interface Source
 */
export interface Source {
    /**
     * 
     * @type {string}
     * @memberof Source
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof Source
     */
    name: string;
    /**
     * 
     * @type {Inventory}
     * @memberof Source
     */
    inventory?: Inventory;
    /**
     * 
     * @type {Date}
     * @memberof Source
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof Source
     */
    updatedAt: Date;
    /**
     * 
     * @type {boolean}
     * @memberof Source
     */
    onPremises: boolean;
    /**
     * 
     * @type {Agent}
     * @memberof Source
     */
    agent?: Agent;
    /**
     * 
     * @type {Array<Label>}
     * @memberof Source
     */
    labels?: Array<Label>;
    /**
     * 
     * @type {SourceInfra}
     * @memberof Source
     */
    infra?: SourceInfra;
}

/**
 * Check if a given object implements the Source interface.
 */
export function instanceOfSource(value: object): value is Source {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    if (!('onPremises' in value) || value['onPremises'] === undefined) return false;
    return true;
}

export function SourceFromJSON(json: any): Source {
    return SourceFromJSONTyped(json, false);
}

export function SourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): Source {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'inventory': json['inventory'] == null ? undefined : InventoryFromJSON(json['inventory']),
        'createdAt': (new Date(json['createdAt'])),
        'updatedAt': (new Date(json['updatedAt'])),
        'onPremises': json['onPremises'],
        'agent': json['agent'] == null ? undefined : AgentFromJSON(json['agent']),
        'labels': json['labels'] == null ? undefined : ((json['labels'] as Array<any>).map(LabelFromJSON)),
        'infra': json['infra'] == null ? undefined : SourceInfraFromJSON(json['infra']),
    };
}

export function SourceToJSON(json: any): Source {
    return SourceToJSONTyped(json, false);
}

export function SourceToJSONTyped(value?: Source | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'inventory': InventoryToJSON(value['inventory']),
        'createdAt': value['createdAt'].toISOString(),
        'updatedAt': value['updatedAt'].toISOString(),
        'onPremises': value['onPremises'],
        'agent': AgentToJSON(value['agent']),
        'labels': value['labels'] == null ? undefined : ((value['labels'] as Array<any>).map(LabelToJSON)),
        'infra': SourceInfraToJSON(value['infra']),
    };
}

