/* tslint:disable */
/* eslint-disable */
/**
 * Migration Planner API - agent endpoint
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: undefined
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { Inventory } from './Inventory.js';
import {
    InventoryFromJSON,
    InventoryFromJSONTyped,
    InventoryToJSON,
    InventoryToJSONTyped,
} from './Inventory.js';

/**
 * 
 * @export
 * @interface SourceStatusUpdate
 */
export interface SourceStatusUpdate {
    /**
     * 
     * @type {string}
     * @memberof SourceStatusUpdate
     */
    agentId: string;
    /**
     * 
     * @type {Inventory}
     * @memberof SourceStatusUpdate
     */
    inventory: Inventory;
}

/**
 * Check if a given object implements the SourceStatusUpdate interface.
 */
export function instanceOfSourceStatusUpdate(value: object): value is SourceStatusUpdate {
    if (!('agentId' in value) || value['agentId'] === undefined) return false;
    if (!('inventory' in value) || value['inventory'] === undefined) return false;
    return true;
}

export function SourceStatusUpdateFromJSON(json: any): SourceStatusUpdate {
    return SourceStatusUpdateFromJSONTyped(json, false);
}

export function SourceStatusUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): SourceStatusUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'agentId': json['agentId'],
        'inventory': InventoryFromJSON(json['inventory']),
    };
}

export function SourceStatusUpdateToJSON(json: any): SourceStatusUpdate {
    return SourceStatusUpdateToJSONTyped(json, false);
}

export function SourceStatusUpdateToJSONTyped(value?: SourceStatusUpdate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'agentId': value['agentId'],
        'inventory': InventoryToJSON(value['inventory']),
    };
}

