/* tslint:disable */
/* eslint-disable */
/**
 * Assisted Migration Agent API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface UpdateGroupRequest
 */
export interface UpdateGroupRequest {
    /**
     * Group display name
     * @type {string}
     * @memberof UpdateGroupRequest
     */
    name?: string;
    /**
     * Optional group description
     * @type {string}
     * @memberof UpdateGroupRequest
     */
    description?: string;
    /**
     * Filter expression (will be validated)
     * @type {string}
     * @memberof UpdateGroupRequest
     */
    filter?: string;
}

/**
 * Check if a given object implements the UpdateGroupRequest interface.
 */
export function instanceOfUpdateGroupRequest(value: object): value is UpdateGroupRequest {
    return true;
}

export function UpdateGroupRequestFromJSON(json: any): UpdateGroupRequest {
    return UpdateGroupRequestFromJSONTyped(json, false);
}

export function UpdateGroupRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateGroupRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'filter': json['filter'] == null ? undefined : json['filter'],
    };
}

export function UpdateGroupRequestToJSON(json: any): UpdateGroupRequest {
    return UpdateGroupRequestToJSONTyped(json, false);
}

export function UpdateGroupRequestToJSONTyped(value?: UpdateGroupRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
        'filter': value['filter'],
    };
}

