/* tslint:disable */
/* eslint-disable */
/**
 * Assisted Migration Agent API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface VcenterCredentials
 */
export interface VcenterCredentials {
    /**
     * vCenter URL
     * @type {string}
     * @memberof VcenterCredentials
     */
    url: string;
    /**
     * 
     * @type {string}
     * @memberof VcenterCredentials
     */
    username: string;
    /**
     * 
     * @type {string}
     * @memberof VcenterCredentials
     */
    password: string;
}

/**
 * Check if a given object implements the VcenterCredentials interface.
 */
export function instanceOfVcenterCredentials(value: object): value is VcenterCredentials {
    if (!('url' in value) || value['url'] === undefined) return false;
    if (!('username' in value) || value['username'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    return true;
}

export function VcenterCredentialsFromJSON(json: any): VcenterCredentials {
    return VcenterCredentialsFromJSONTyped(json, false);
}

export function VcenterCredentialsFromJSONTyped(json: any, ignoreDiscriminator: boolean): VcenterCredentials {
    if (json == null) {
        return json;
    }
    return {
        
        'url': json['url'],
        'username': json['username'],
        'password': json['password'],
    };
}

export function VcenterCredentialsToJSON(json: any): VcenterCredentials {
    return VcenterCredentialsToJSONTyped(json, false);
}

export function VcenterCredentialsToJSONTyped(value?: VcenterCredentials | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'url': value['url'],
        'username': value['username'],
        'password': value['password'],
    };
}

