/* tslint:disable */
/* eslint-disable */
/**
 * Assisted Migration Agent API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface VddkPost200Response
 */
export interface VddkPost200Response {
    /**
     * md5 sum of the uploaded tarball
     * @type {string}
     * @memberof VddkPost200Response
     */
    md5: string;
    /**
     * written bytes
     * @type {number}
     * @memberof VddkPost200Response
     */
    bytes: number;
}

/**
 * Check if a given object implements the VddkPost200Response interface.
 */
export function instanceOfVddkPost200Response(value: object): value is VddkPost200Response {
    if (!('md5' in value) || value['md5'] === undefined) return false;
    if (!('bytes' in value) || value['bytes'] === undefined) return false;
    return true;
}

export function VddkPost200ResponseFromJSON(json: any): VddkPost200Response {
    return VddkPost200ResponseFromJSONTyped(json, false);
}

export function VddkPost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): VddkPost200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'md5': json['md5'],
        'bytes': json['bytes'],
    };
}

export function VddkPost200ResponseToJSON(json: any): VddkPost200Response {
    return VddkPost200ResponseToJSONTyped(json, false);
}

export function VddkPost200ResponseToJSONTyped(value?: VddkPost200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'md5': value['md5'],
        'bytes': value['bytes'],
    };
}

