/* tslint:disable */
/* eslint-disable */
/**
 * Assisted Migration Agent API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface VersionInfo
 */
export interface VersionInfo {
    /**
     * Agent version (e.g. v2.0.0)
     * @type {string}
     * @memberof VersionInfo
     */
    version: string;
    /**
     * Git commit SHA used to build the agent
     * @type {string}
     * @memberof VersionInfo
     */
    gitCommit: string;
}

/**
 * Check if a given object implements the VersionInfo interface.
 */
export function instanceOfVersionInfo(value: object): value is VersionInfo {
    if (!('version' in value) || value['version'] === undefined) return false;
    if (!('gitCommit' in value) || value['gitCommit'] === undefined) return false;
    return true;
}

export function VersionInfoFromJSON(json: any): VersionInfo {
    return VersionInfoFromJSONTyped(json, false);
}

export function VersionInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): VersionInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'version': json['version'],
        'gitCommit': json['gitCommit'],
    };
}

export function VersionInfoToJSON(json: any): VersionInfo {
    return VersionInfoToJSONTyped(json, false);
}

export function VersionInfoToJSONTyped(value?: VersionInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'version': value['version'],
        'gitCommit': value['gitCommit'],
    };
}

