/* tslint:disable */
/* eslint-disable */
/**
 * Migration Planner Agent UI API
 * API endpoints for the agent UI to interact with the migration discovery VM
 *
 * The version of the OpenAPI document: undefined
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface VersionReply
 */
export interface VersionReply {
    /**
     * Version of the agent
     * @type {string}
     * @memberof VersionReply
     */
    version: string;
}

/**
 * Check if a given object implements the VersionReply interface.
 */
export function instanceOfVersionReply(value: object): value is VersionReply {
    if (!('version' in value) || value['version'] === undefined) return false;
    return true;
}

export function VersionReplyFromJSON(json: any): VersionReply {
    return VersionReplyFromJSONTyped(json, false);
}

export function VersionReplyFromJSONTyped(json: any, ignoreDiscriminator: boolean): VersionReply {
    if (json == null) {
        return json;
    }
    return {
        
        'version': json['version'],
    };
}

export function VersionReplyToJSON(json: any): VersionReply {
    return VersionReplyToJSONTyped(json, false);
}

export function VersionReplyToJSONTyped(value?: VersionReply | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'version': value['version'],
    };
}

