/* tslint:disable */
/* eslint-disable */
/**
 * Assisted Migration Agent API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { VmInspectionStatus } from './VmInspectionStatus.js';
import {
    VmInspectionStatusFromJSON,
    VmInspectionStatusFromJSONTyped,
    VmInspectionStatusToJSON,
    VmInspectionStatusToJSONTyped,
} from './VmInspectionStatus.js';

/**
 * 
 * @export
 * @interface VM
 */
export interface VM {
    /**
     * VM name
     * @type {string}
     * @memberof VM
     */
    name: string;
    /**
     * VM ID
     * @type {string}
     * @memberof VM
     */
    id: string;
    /**
     * vCenter state (e.g., poweredOn, poweredOff, suspended)
     * @type {string}
     * @memberof VM
     */
    vCenterState: string;
    /**
     * Cluster name
     * @type {string}
     * @memberof VM
     */
    cluster: string;
    /**
     * Total disk size in MB
     * @type {number}
     * @memberof VM
     */
    diskSize: number;
    /**
     * Memory size in MB
     * @type {number}
     * @memberof VM
     */
    memory: number;
    /**
     * Number of issues found for this VM
     * @type {number}
     * @memberof VM
     */
    issueCount: number;
    /**
     * 
     * @type {VmInspectionStatus}
     * @memberof VM
     */
    inspection: VmInspectionStatus;
}

/**
 * Check if a given object implements the VM interface.
 */
export function instanceOfVM(value: object): value is VM {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('vCenterState' in value) || value['vCenterState'] === undefined) return false;
    if (!('cluster' in value) || value['cluster'] === undefined) return false;
    if (!('diskSize' in value) || value['diskSize'] === undefined) return false;
    if (!('memory' in value) || value['memory'] === undefined) return false;
    if (!('issueCount' in value) || value['issueCount'] === undefined) return false;
    if (!('inspection' in value) || value['inspection'] === undefined) return false;
    return true;
}

export function VMFromJSON(json: any): VM {
    return VMFromJSONTyped(json, false);
}

export function VMFromJSONTyped(json: any, ignoreDiscriminator: boolean): VM {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'id': json['id'],
        'vCenterState': json['vCenterState'],
        'cluster': json['cluster'],
        'diskSize': json['diskSize'],
        'memory': json['memory'],
        'issueCount': json['issueCount'],
        'inspection': VmInspectionStatusFromJSON(json['inspection']),
    };
}

export function VMToJSON(json: any): VM {
    return VMToJSONTyped(json, false);
}

export function VMToJSONTyped(value?: VM | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'id': value['id'],
        'vCenterState': value['vCenterState'],
        'cluster': value['cluster'],
        'diskSize': value['diskSize'],
        'memory': value['memory'],
        'issueCount': value['issueCount'],
        'inspection': VmInspectionStatusToJSON(value['inspection']),
    };
}

