/* tslint:disable */
/* eslint-disable */
/**
 * Assisted Migration Agent API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface VMDevice
 */
export interface VMDevice {
    /**
     * Type of virtual device (e.g., cdrom, floppy, usb, serial, parallel)
     * @type {string}
     * @memberof VMDevice
     */
    kind?: string;
}

/**
 * Check if a given object implements the VMDevice interface.
 */
export function instanceOfVMDevice(value: object): value is VMDevice {
    return true;
}

export function VMDeviceFromJSON(json: any): VMDevice {
    return VMDeviceFromJSONTyped(json, false);
}

export function VMDeviceFromJSONTyped(json: any, ignoreDiscriminator: boolean): VMDevice {
    if (json == null) {
        return json;
    }
    return {
        
        'kind': json['kind'] == null ? undefined : json['kind'],
    };
}

export function VMDeviceToJSON(json: any): VMDevice {
    return VMDeviceToJSONTyped(json, false);
}

export function VMDeviceToJSONTyped(value?: VMDevice | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'kind': value['kind'],
    };
}

