/* tslint:disable */
/* eslint-disable */
/**
 * Assisted Migration Agent API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface VMDisk
 */
export interface VMDisk {
    /**
     * Unique key identifying this disk within the VM
     * @type {number}
     * @memberof VMDisk
     */
    key?: number;
    /**
     * Path to the VMDK file in the datastore
     * @type {string}
     * @memberof VMDisk
     */
    file?: string;
    /**
     * Disk capacity in bytes
     * @type {number}
     * @memberof VMDisk
     */
    capacity?: number;
    /**
     * Whether this disk is shared between multiple VMs
     * @type {boolean}
     * @memberof VMDisk
     */
    shared?: boolean;
    /**
     * Whether this is a Raw Device Mapping (direct LUN access)
     * @type {boolean}
     * @memberof VMDisk
     */
    rdm?: boolean;
    /**
     * Bus type (e.g., scsi, ide, sata, nvme)
     * @type {string}
     * @memberof VMDisk
     */
    bus?: string;
    /**
     * Disk mode (e.g., persistent, independent_persistent, independent_nonpersistent)
     * @type {string}
     * @memberof VMDisk
     */
    mode?: string;
}

/**
 * Check if a given object implements the VMDisk interface.
 */
export function instanceOfVMDisk(value: object): value is VMDisk {
    return true;
}

export function VMDiskFromJSON(json: any): VMDisk {
    return VMDiskFromJSONTyped(json, false);
}

export function VMDiskFromJSONTyped(json: any, ignoreDiscriminator: boolean): VMDisk {
    if (json == null) {
        return json;
    }
    return {
        
        'key': json['key'] == null ? undefined : json['key'],
        'file': json['file'] == null ? undefined : json['file'],
        'capacity': json['capacity'] == null ? undefined : json['capacity'],
        'shared': json['shared'] == null ? undefined : json['shared'],
        'rdm': json['rdm'] == null ? undefined : json['rdm'],
        'bus': json['bus'] == null ? undefined : json['bus'],
        'mode': json['mode'] == null ? undefined : json['mode'],
    };
}

export function VMDiskToJSON(json: any): VMDisk {
    return VMDiskToJSONTyped(json, false);
}

export function VMDiskToJSONTyped(value?: VMDisk | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'key': value['key'],
        'file': value['file'],
        'capacity': value['capacity'],
        'shared': value['shared'],
        'rdm': value['rdm'],
        'bus': value['bus'],
        'mode': value['mode'],
    };
}

