/* tslint:disable */
/* eslint-disable */
/**
 * Assisted Migration Agent API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface VmInspectionStatus
 */
export interface VmInspectionStatus {
    /**
     * Current inspection state
     * @type {string}
     * @memberof VmInspectionStatus
     */
    state: VmInspectionStatusStateEnum;
    /**
     * Error message when state is error
     * @type {string}
     * @memberof VmInspectionStatus
     */
    error?: string;
    /**
     * Inspection results
     * @type {object}
     * @memberof VmInspectionStatus
     */
    results?: object;
}


/**
 * @export
 */
export const VmInspectionStatusStateEnum = {
    Pending: 'pending',
    Running: 'running',
    Completed: 'completed',
    Canceled: 'canceled',
    Error: 'error',
    NotFound: 'not_found'
} as const;
export type VmInspectionStatusStateEnum = typeof VmInspectionStatusStateEnum[keyof typeof VmInspectionStatusStateEnum];


/**
 * Check if a given object implements the VmInspectionStatus interface.
 */
export function instanceOfVmInspectionStatus(value: object): value is VmInspectionStatus {
    if (!('state' in value) || value['state'] === undefined) return false;
    return true;
}

export function VmInspectionStatusFromJSON(json: any): VmInspectionStatus {
    return VmInspectionStatusFromJSONTyped(json, false);
}

export function VmInspectionStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): VmInspectionStatus {
    if (json == null) {
        return json;
    }
    return {
        
        'state': json['state'],
        'error': json['error'] == null ? undefined : json['error'],
        'results': json['results'] == null ? undefined : json['results'],
    };
}

export function VmInspectionStatusToJSON(json: any): VmInspectionStatus {
    return VmInspectionStatusToJSONTyped(json, false);
}

export function VmInspectionStatusToJSONTyped(value?: VmInspectionStatus | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'state': value['state'],
        'error': value['error'],
        'results': value['results'],
    };
}

