/* tslint:disable */
/* eslint-disable */
/**
 * Assisted Migration Agent API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface VMIssue
 */
export interface VMIssue {
    /**
     * Short label describing the issue
     * @type {string}
     * @memberof VMIssue
     */
    label: string;
    /**
     * Detailed description of the issue with additional context and recommendations
     * @type {string}
     * @memberof VMIssue
     */
    description: string;
    /**
     * Severity category of the issue. Unknown categories are mapped to 'Other'.
     * @type {string}
     * @memberof VMIssue
     */
    category: VMIssueCategoryEnum;
}


/**
 * @export
 */
export const VMIssueCategoryEnum = {
    Critical: 'Critical',
    Warning: 'Warning',
    Information: 'Information',
    Advisory: 'Advisory',
    Error: 'Error',
    Other: 'Other'
} as const;
export type VMIssueCategoryEnum = typeof VMIssueCategoryEnum[keyof typeof VMIssueCategoryEnum];


/**
 * Check if a given object implements the VMIssue interface.
 */
export function instanceOfVMIssue(value: object): value is VMIssue {
    if (!('label' in value) || value['label'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('category' in value) || value['category'] === undefined) return false;
    return true;
}

export function VMIssueFromJSON(json: any): VMIssue {
    return VMIssueFromJSONTyped(json, false);
}

export function VMIssueFromJSONTyped(json: any, ignoreDiscriminator: boolean): VMIssue {
    if (json == null) {
        return json;
    }
    return {
        
        'label': json['label'],
        'description': json['description'],
        'category': json['category'],
    };
}

export function VMIssueToJSON(json: any): VMIssue {
    return VMIssueToJSONTyped(json, false);
}

export function VMIssueToJSONTyped(value?: VMIssue | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'label': value['label'],
        'description': value['description'],
        'category': value['category'],
    };
}

