/* tslint:disable */
/* eslint-disable */
/**
 * Assisted Migration Agent API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface VMNIC
 */
export interface VMNIC {
    /**
     * MAC address of the virtual NIC
     * @type {string}
     * @memberof VMNIC
     */
    mac?: string;
    /**
     * Reference to the network this NIC is connected to
     * @type {string}
     * @memberof VMNIC
     */
    network?: string;
    /**
     * Index of the NIC within the VM
     * @type {number}
     * @memberof VMNIC
     */
    index?: number;
}

/**
 * Check if a given object implements the VMNIC interface.
 */
export function instanceOfVMNIC(value: object): value is VMNIC {
    return true;
}

export function VMNICFromJSON(json: any): VMNIC {
    return VMNICFromJSONTyped(json, false);
}

export function VMNICFromJSONTyped(json: any, ignoreDiscriminator: boolean): VMNIC {
    if (json == null) {
        return json;
    }
    return {
        
        'mac': json['mac'] == null ? undefined : json['mac'],
        'network': json['network'] == null ? undefined : json['network'],
        'index': json['index'] == null ? undefined : json['index'],
    };
}

export function VMNICToJSON(json: any): VMNIC {
    return VMNICToJSONTyped(json, false);
}

export function VMNICToJSONTyped(value?: VMNIC | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'mac': value['mac'],
        'network': value['network'],
        'index': value['index'],
    };
}

