/* tslint:disable */
/* eslint-disable */
/**
 * Migration Planner API
 * Based on: https://github.com/kubev2v/migration-planner/blob/381e0e2f0d99c996a1230d27470988d7cbe9e282/api/v1alpha1/openapi.yaml
 *
 * The version of the OpenAPI document: 0.4.0-381e0e2f
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime.js';
import type {
  Assessment,
  AssessmentForm,
  AssessmentUpdate,
  ClusterRequirementsRequest,
  ClusterRequirementsResponse,
} from '../models/index.js';
import {
    AssessmentFromJSON,
    AssessmentToJSON,
    AssessmentFormFromJSON,
    AssessmentFormToJSON,
    AssessmentUpdateFromJSON,
    AssessmentUpdateToJSON,
    ClusterRequirementsRequestFromJSON,
    ClusterRequirementsRequestToJSON,
    ClusterRequirementsResponseFromJSON,
    ClusterRequirementsResponseToJSON,
} from '../models/index.js';

export interface CalculateAssessmentClusterRequirementsRequest {
    id: string;
    clusterRequirementsRequest: ClusterRequirementsRequest;
}

export interface CreateAssessmentRequest {
    assessmentForm: AssessmentForm;
}

export interface DeleteAssessmentRequest {
    id: string;
}

export interface GetAssessmentRequest {
    id: string;
}

export interface UpdateAssessmentRequest {
    id: string;
    assessmentUpdate: AssessmentUpdate;
}

/**
 * AssessmentApi - interface
 * 
 * @export
 * @interface AssessmentApiInterface
 */
export interface AssessmentApiInterface {
    /**
     * Calculate cluster requirements for an assessment
     * @param {string} id ID of the assessment
     * @param {ClusterRequirementsRequest} clusterRequirementsRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AssessmentApiInterface
     */
    calculateAssessmentClusterRequirementsRaw(requestParameters: CalculateAssessmentClusterRequirementsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ClusterRequirementsResponse>>;

    /**
     * Calculate cluster requirements for an assessment
     */
    calculateAssessmentClusterRequirements(requestParameters: CalculateAssessmentClusterRequirementsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ClusterRequirementsResponse>;

    /**
     * Create an assessment
     * @param {AssessmentForm} assessmentForm 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AssessmentApiInterface
     */
    createAssessmentRaw(requestParameters: CreateAssessmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Assessment>>;

    /**
     * Create an assessment
     */
    createAssessment(requestParameters: CreateAssessmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Assessment>;

    /**
     * Delete an assessment
     * @param {string} id ID of the assessment
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AssessmentApiInterface
     */
    deleteAssessmentRaw(requestParameters: DeleteAssessmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Assessment>>;

    /**
     * Delete an assessment
     */
    deleteAssessment(requestParameters: DeleteAssessmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Assessment>;

    /**
     * Get the specified assessment
     * @param {string} id ID of the assessment
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AssessmentApiInterface
     */
    getAssessmentRaw(requestParameters: GetAssessmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Assessment>>;

    /**
     * Get the specified assessment
     */
    getAssessment(requestParameters: GetAssessmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Assessment>;

    /**
     * List assessments
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AssessmentApiInterface
     */
    listAssessmentsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Assessment>>>;

    /**
     * List assessments
     */
    listAssessments(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Assessment>>;

    /**
     * Update an assessment
     * @param {string} id ID of the assessment
     * @param {AssessmentUpdate} assessmentUpdate 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AssessmentApiInterface
     */
    updateAssessmentRaw(requestParameters: UpdateAssessmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Assessment>>;

    /**
     * Update an assessment
     */
    updateAssessment(requestParameters: UpdateAssessmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Assessment>;

}

/**
 * 
 */
export class AssessmentApi extends runtime.BaseAPI implements AssessmentApiInterface {

    /**
     * Calculate cluster requirements for an assessment
     */
    async calculateAssessmentClusterRequirementsRaw(requestParameters: CalculateAssessmentClusterRequirementsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ClusterRequirementsResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling calculateAssessmentClusterRequirements().'
            );
        }

        if (requestParameters['clusterRequirementsRequest'] == null) {
            throw new runtime.RequiredError(
                'clusterRequirementsRequest',
                'Required parameter "clusterRequirementsRequest" was null or undefined when calling calculateAssessmentClusterRequirements().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/assessments/{id}/cluster-requirements`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ClusterRequirementsRequestToJSON(requestParameters['clusterRequirementsRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ClusterRequirementsResponseFromJSON(jsonValue));
    }

    /**
     * Calculate cluster requirements for an assessment
     */
    async calculateAssessmentClusterRequirements(requestParameters: CalculateAssessmentClusterRequirementsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ClusterRequirementsResponse> {
        const response = await this.calculateAssessmentClusterRequirementsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create an assessment
     */
    async createAssessmentRaw(requestParameters: CreateAssessmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Assessment>> {
        if (requestParameters['assessmentForm'] == null) {
            throw new runtime.RequiredError(
                'assessmentForm',
                'Required parameter "assessmentForm" was null or undefined when calling createAssessment().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/assessments`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AssessmentFormToJSON(requestParameters['assessmentForm']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AssessmentFromJSON(jsonValue));
    }

    /**
     * Create an assessment
     */
    async createAssessment(requestParameters: CreateAssessmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Assessment> {
        const response = await this.createAssessmentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete an assessment
     */
    async deleteAssessmentRaw(requestParameters: DeleteAssessmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Assessment>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteAssessment().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/assessments/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AssessmentFromJSON(jsonValue));
    }

    /**
     * Delete an assessment
     */
    async deleteAssessment(requestParameters: DeleteAssessmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Assessment> {
        const response = await this.deleteAssessmentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get the specified assessment
     */
    async getAssessmentRaw(requestParameters: GetAssessmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Assessment>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getAssessment().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/assessments/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AssessmentFromJSON(jsonValue));
    }

    /**
     * Get the specified assessment
     */
    async getAssessment(requestParameters: GetAssessmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Assessment> {
        const response = await this.getAssessmentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List assessments
     */
    async listAssessmentsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Assessment>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/assessments`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(AssessmentFromJSON));
    }

    /**
     * List assessments
     */
    async listAssessments(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Assessment>> {
        const response = await this.listAssessmentsRaw(initOverrides);
        return await response.value();
    }

    /**
     * Update an assessment
     */
    async updateAssessmentRaw(requestParameters: UpdateAssessmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Assessment>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling updateAssessment().'
            );
        }

        if (requestParameters['assessmentUpdate'] == null) {
            throw new runtime.RequiredError(
                'assessmentUpdate',
                'Required parameter "assessmentUpdate" was null or undefined when calling updateAssessment().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/assessments/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: AssessmentUpdateToJSON(requestParameters['assessmentUpdate']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AssessmentFromJSON(jsonValue));
    }

    /**
     * Update an assessment
     */
    async updateAssessment(requestParameters: UpdateAssessmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Assessment> {
        const response = await this.updateAssessmentRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
