/* tslint:disable */
/* eslint-disable */
/**
 * Migration Planner API
 * Based on: https://github.com/kubev2v/migration-planner/blob/bd435bf4e63611a5d609f7c918e85dd57830fccf/api/v1alpha1/openapi.yaml
 *
 * The version of the OpenAPI document: 0.4.0-bd435bf4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime.js';
import type {
  PresignedUrl,
} from '../models/index.js';
import {
    PresignedUrlFromJSON,
    PresignedUrlToJSON,
} from '../models/index.js';

export interface GetSourceDownloadURLRequest {
    id: string;
}

export interface HeadImageRequest {
    id: string;
}

/**
 * ImageApi - interface
 * 
 * @export
 * @interface ImageApiInterface
 */
export interface ImageApiInterface {
    /**
     * Get the OVA image via URL
     * @param {string} id Source id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ImageApiInterface
     */
    getSourceDownloadURLRaw(requestParameters: GetSourceDownloadURLRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PresignedUrl>>;

    /**
     * Get the OVA image via URL
     */
    getSourceDownloadURL(requestParameters: GetSourceDownloadURLRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PresignedUrl>;

    /**
     * Head the OVA image
     * @param {string} id Id of the source
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ImageApiInterface
     */
    headImageRaw(requestParameters: HeadImageRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Head the OVA image
     */
    headImage(requestParameters: HeadImageRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

}

/**
 * 
 */
export class ImageApi extends runtime.BaseAPI implements ImageApiInterface {

    /**
     * Get the OVA image via URL
     */
    async getSourceDownloadURLRaw(requestParameters: GetSourceDownloadURLRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PresignedUrl>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getSourceDownloadURL().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/sources/{id}/image-url`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PresignedUrlFromJSON(jsonValue));
    }

    /**
     * Get the OVA image via URL
     */
    async getSourceDownloadURL(requestParameters: GetSourceDownloadURLRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PresignedUrl> {
        const response = await this.getSourceDownloadURLRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Head the OVA image
     */
    async headImageRaw(requestParameters: HeadImageRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling headImage().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/sources/{id}/image`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'HEAD',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Head the OVA image
     */
    async headImage(requestParameters: HeadImageRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.headImageRaw(requestParameters, initOverrides);
    }

}
