/* tslint:disable */
/* eslint-disable */
/**
 * Migration Planner API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: undefined
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Source,
  SourceCreate,
  SourceUpdateOnPrem,
  Status,
  UploadRvtoolsFile200Response,
} from '../models/index';
import {
    SourceFromJSON,
    SourceToJSON,
    SourceCreateFromJSON,
    SourceCreateToJSON,
    SourceUpdateOnPremFromJSON,
    SourceUpdateOnPremToJSON,
    StatusFromJSON,
    StatusToJSON,
    UploadRvtoolsFile200ResponseFromJSON,
    UploadRvtoolsFile200ResponseToJSON,
} from '../models/index';

export interface CreateSourceRequest {
    sourceCreate: SourceCreate;
}

export interface DeleteSourceRequest {
    id: string;
}

export interface GetSourceRequest {
    id: string;
}

export interface ListSourcesRequest {
    includeDefault?: boolean;
}

export interface UpdateSourceRequest {
    id: string;
    sourceUpdateOnPrem: SourceUpdateOnPrem;
}

export interface UploadRvtoolsFileRequest {
    id: string;
    file: Blob;
}

/**
 * SourceApi - interface
 * 
 * @export
 * @interface SourceApiInterface
 */
export interface SourceApiInterface {
    /**
     * Create a source
     * @param {SourceCreate} sourceCreate 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SourceApiInterface
     */
    createSourceRaw(requestParameters: CreateSourceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Source>>;

    /**
     * Create a source
     */
    createSource(requestParameters: CreateSourceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Source>;

    /**
     * Delete a source
     * @param {string} id ID of the source
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SourceApiInterface
     */
    deleteSourceRaw(requestParameters: DeleteSourceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Source>>;

    /**
     * Delete a source
     */
    deleteSource(requestParameters: DeleteSourceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Source>;

    /**
     * delete a collection of sources
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SourceApiInterface
     */
    deleteSourcesRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Status>>;

    /**
     * delete a collection of sources
     */
    deleteSources(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Status>;

    /**
     * Get the specified source
     * @param {string} id ID of the source
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SourceApiInterface
     */
    getSourceRaw(requestParameters: GetSourceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Source>>;

    /**
     * Get the specified source
     */
    getSource(requestParameters: GetSourceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Source>;

    /**
     * List sources
     * @param {boolean} [includeDefault] control whatever the default report should be added to the result
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SourceApiInterface
     */
    listSourcesRaw(requestParameters: ListSourcesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Source>>>;

    /**
     * List sources
     */
    listSources(requestParameters: ListSourcesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Source>>;

    /**
     * Update a source from inventory file
     * @param {string} id ID of the source
     * @param {SourceUpdateOnPrem} sourceUpdateOnPrem 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SourceApiInterface
     */
    updateSourceRaw(requestParameters: UpdateSourceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Source>>;

    /**
     * Update a source from inventory file
     */
    updateSource(requestParameters: UpdateSourceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Source>;

    /**
     * Update a source by uploading an RVTools file directly
     * @param {string} id ID of the source
     * @param {Blob} file The RVTools file (Excel)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SourceApiInterface
     */
    uploadRvtoolsFileRaw(requestParameters: UploadRvtoolsFileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UploadRvtoolsFile200Response>>;

    /**
     * Update a source by uploading an RVTools file directly
     */
    uploadRvtoolsFile(requestParameters: UploadRvtoolsFileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UploadRvtoolsFile200Response>;

}

/**
 * 
 */
export class SourceApi extends runtime.BaseAPI implements SourceApiInterface {

    /**
     * Create a source
     */
    async createSourceRaw(requestParameters: CreateSourceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Source>> {
        if (requestParameters['sourceCreate'] == null) {
            throw new runtime.RequiredError(
                'sourceCreate',
                'Required parameter "sourceCreate" was null or undefined when calling createSource().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/v1/sources`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SourceCreateToJSON(requestParameters['sourceCreate']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SourceFromJSON(jsonValue));
    }

    /**
     * Create a source
     */
    async createSource(requestParameters: CreateSourceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Source> {
        const response = await this.createSourceRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete a source
     */
    async deleteSourceRaw(requestParameters: DeleteSourceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Source>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteSource().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/sources/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SourceFromJSON(jsonValue));
    }

    /**
     * Delete a source
     */
    async deleteSource(requestParameters: DeleteSourceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Source> {
        const response = await this.deleteSourceRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * delete a collection of sources
     */
    async deleteSourcesRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Status>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/sources`,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StatusFromJSON(jsonValue));
    }

    /**
     * delete a collection of sources
     */
    async deleteSources(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Status> {
        const response = await this.deleteSourcesRaw(initOverrides);
        return await response.value();
    }

    /**
     * Get the specified source
     */
    async getSourceRaw(requestParameters: GetSourceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Source>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getSource().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/sources/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SourceFromJSON(jsonValue));
    }

    /**
     * Get the specified source
     */
    async getSource(requestParameters: GetSourceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Source> {
        const response = await this.getSourceRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List sources
     */
    async listSourcesRaw(requestParameters: ListSourcesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Source>>> {
        const queryParameters: any = {};

        if (requestParameters['includeDefault'] != null) {
            queryParameters['include_default'] = requestParameters['includeDefault'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/sources`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(SourceFromJSON));
    }

    /**
     * List sources
     */
    async listSources(requestParameters: ListSourcesRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Source>> {
        const response = await this.listSourcesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update a source from inventory file
     */
    async updateSourceRaw(requestParameters: UpdateSourceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Source>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling updateSource().'
            );
        }

        if (requestParameters['sourceUpdateOnPrem'] == null) {
            throw new runtime.RequiredError(
                'sourceUpdateOnPrem',
                'Required parameter "sourceUpdateOnPrem" was null or undefined when calling updateSource().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/v1/sources/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: SourceUpdateOnPremToJSON(requestParameters['sourceUpdateOnPrem']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SourceFromJSON(jsonValue));
    }

    /**
     * Update a source from inventory file
     */
    async updateSource(requestParameters: UpdateSourceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Source> {
        const response = await this.updateSourceRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update a source by uploading an RVTools file directly
     */
    async uploadRvtoolsFileRaw(requestParameters: UploadRvtoolsFileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UploadRvtoolsFile200Response>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling uploadRvtoolsFile().'
            );
        }

        if (requestParameters['file'] == null) {
            throw new runtime.RequiredError(
                'file',
                'Required parameter "file" was null or undefined when calling uploadRvtoolsFile().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['file'] != null) {
            formParams.append('file', requestParameters['file'] as any);
        }

        const response = await this.request({
            path: `/api/v1/sources/{id}/rvtools`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UploadRvtoolsFile200ResponseFromJSON(jsonValue));
    }

    /**
     * Update a source by uploading an RVTools file directly
     */
    async uploadRvtoolsFile(requestParameters: UploadRvtoolsFileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UploadRvtoolsFile200Response> {
        const response = await this.uploadRvtoolsFileRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
