apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/kubev2v/migration-planner-agent-ui?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: "{{revision}}"
    build.appstudio.redhat.com/target_branch: "{{target_branch}}"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression:
      event == "push" && target_branch
      == "main"
  labels:
    appstudio.openshift.io/application: assisted-migration
    appstudio.openshift.io/component: migration-planner-agent-ui
    pipelines.appstudio.openshift.io/type: build
  name: migration-planner-agent-ui-on-push
  namespace: assisted-migration-tenant
spec:
  params:
    - name: git-url
      value: "{{source_url}}"
    - name: revision
      value: "{{revision}}"
    - name: output-image
      value: quay.io/redhat-user-workloads/assisted-migration-tenant/migration-planner-agent-ui:{{revision}}
    - name: image-expires-after
      value: ""
    - name: dockerfile
      value: Containerfile
    - name: path-context
      value: .
    - name: build-source-image
      value: "true"
  pipelineRef:
    name: docker-build
  taskRunSpecs:
    - pipelineTaskName: build-container
      stepSpecs:
        - name: build
          computeResources:
            requests:
              memory: 2Gi
              cpu: "1"
  finally:
    - name: tag-latest
      params:
        - name: IMAGE
          value: quay.io/redhat-user-workloads/assisted-migration-tenant/migration-planner-agent-ui:{{revision}}
        - name: TLSVERIFY
          value: "true"
        - name: EXTRA_ARGS
          value:
            - "--dest-tag"
            - "latest"
      taskRef:
        resolver: bundles
        params:
          - name: name
            value: skopeo-copy
          - name: bundle
            value: quay.io/konflux-ci/tekton-catalog/task-skopeo-copy:0.1
          - name: kind
            value: task
  workspaces:
    - name: workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
    - name: git-auth
      secret:
        secretName: "{{ git_auth_secret }}"
