name: Sync Release Branch

on:
  push:
    branches:
      - main
      - stable

permissions:
  contents: write

jobs:
  sync:
    name: Sync Release Branch
    uses: kubev2v/migration-planner-workflows/.github/workflows/sync-release-branch.yml@b5de744cc45e4daaf9e28dcd6b179ab4a8ad7c7c # main
    secrets: inherit
